### ISSUE TITLE
Cells execute in parallel

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#1015]
### Describe the bug
I can execute all cell and they might overlap as they do not wait for the current submission to complete

Expected 
![image](https://user-images.githubusercontent.com/375556/106017454-60d8c500-60b8-11eb-899f-67d0bab879eb.png)

Actual
![image](https://user-images.githubusercontent.com/375556/106017512-6df5b400-60b8-11eb-8ac0-bc2d8947fc09.png)

![image](https://user-images.githubusercontent.com/375556/106017572-7ea62a00-60b8-11eb-9560-791a1d7ee29f.png)

Repro notebook attached
[cell_execution_overlapping.zip](https://github.com/dotnet/interactive/files/5881404/cell_execution_overlapping.zip)

### Please complete the following:

**Which version of .NET Interactive are you using?** :

![image](https://user-images.githubusercontent.com/375556/106017214-23743780-60b8-11eb-83d0-edf2a6df01e3.png)

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

**Comment by colombod** [comment]
@idg10

**Comment by cveld** [comment]
What was the conclusion here? Is parallel execution supported? I have some long running PowerShell scripts which should ideally run in parallel. But I get this error when the top most completes:

`Error: System.Management.Automation.InvalidPowerShellStateException: The state of the current PowerShell instance is not valid for this operation.
at System.Management.Automation.PowerShell.AssertChangesAreAccepted()
at System.Management.Automation.PSCommand.AddCommand(Command command)
at System.Management.Automation.PowerShell.AddCommand(CommandInfo commandInfo)
at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel.ReportError(ErrorRecord error) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 401
at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel.ReportException(Exception e) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 412
at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel.RunSubmitCodeLocally(String code) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 379
at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel.Microsoft.DotNet.Interactive.IKernelCommandHandler<Microsoft.DotNet.Interactive.Commands.SubmitCode>.HandleAsync(SubmitCode submitCode, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 282
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 326
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 51`
