### ISSUE TITLE
Notebook with SQL Connection SQL Server failed

### ISSUE THREAD

**Issue by kkbruce** [dotnet/interactive#1399]
### Describe the bug

Follow document https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/ step, can't connect to SQL Server.

### Please complete the following:

**Which version of .NET Interactive are you using?**

* In a notebook, run the `#!about` magic command. 

.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.225602+88e6d92f1cf8ead1c4c0b982e67b4a63902e00e6
Build date: 2021-05-27T09:16:11.3076724Z
https://github.com/dotnet/interactive

* At the command line, run `dotnet interactive --version`.

1.0.230701+897ec27256aa312cc872b52b261726684b29d42b

- OS
    - [x] Windows 10
 - Browser 
    - [x] Chrome
    - [x] Edge
 - Frontend
    - [x] Visual Studio Code 

### Screenshots

step1

we need to run it on Intranet, so download https://www.nuget.org/packages/Microsoft.DotNet.Interactive.SqlServer/ package, version 1.0.0-beta.21255.3

step2: 

```
#!csharp
#i "nuget:Z:\NuGetPackate\"
#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"
```

Step3: 

```
#!connect mssql -h
```

we can see the description of the command.

```
mssql
  Connects to a Microsoft SQL Server database

Usage:
  [options] #!connect mssql <connectionString>

Arguments:
  <connectionString>  The connection string used to connect to the database

Options:
  --create-dbcontext           Scaffold a DbContext in the C# kernel.
  --kernel-name <kernel-name>  The name of the subkernel to be added
  -?, -h, --help               Show help and usage information
```

Step4

```
#!connect mssql "server=xxx;database=yyy;user id=id;password=pwd;trusted_connection=False;connection timeout=1000;Application Name=test"
```

At this stage, there will be a mistake:

```
Error: System.InvalidCastException: Unable to cast object of type 'Microsoft.DotNet.Interactive.SQLKernel' to type 'Microsoft.DotNet.Interactive.ISupportNuget'.
at Microsoft.DotNet.Interactive.SqlServer.MsSqlKernelConnection.CreateKernelAsync(MsSqlConnectionOptions options, KernelInvocationContext context)
at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass27_0`1.<<AddKernelConnection>b__0>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 346
--- End of stack trace from previous location ---
at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 35
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 246
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 57
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 149
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 48
```

**Comment by jonsequitur** [comment]
Could you add the output from running `dotnet --info` in your terminal?

Thanks.

**Comment by kkbruce** [comment]
Hi @jonsequitur 

```
dotnet --version
5.0.300
```

**Comment by jonsequitur** [comment]
`dotnet --info` if you could. I'm wondering what other SDKs you have installed.

**Comment by kkbruce** [comment]
@jonsequitur 

```
dotnet --info
.NET SDK (反映任何 global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

執行階段環境:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by jonsequitur** [comment]
Interesting. We had thought this bug only affected people with a .NET 6 preview SDK installed. 

@KevinRansom 👀

@kkbruce, if you run `dotnet nuget list source`, does `  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json` show up by any chance?

**Comment by kkbruce** [comment]
@jonsequitur 

There is no such location on the list. Do I need to add it manually to test?

```
dotnet nuget list source

已註冊的來源:
  1.  nuget.org [已啟用]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [已啟用]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by kkbruce** [comment]
I run `dotnet nuget add source -n dotnetTools https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json` to add dotnet-tools source.

The first step will go wrong:

```
#!csharp
#i "nuget:C:\Tools\NuGetPackate\"
#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"
```

response

```
Restore sources

C:\Tools\NuGetPackate\

Installed package Microsoft.DotNet.Interactive.SqlServer version 1.0.0-beta.21309.6
Error: System.TypeLoadException: Could not load type 'Microsoft.DotNet.Interactive.Formatting.TabularData.TabularDataResource' from assembly 'Microsoft.DotNet.Interactive.Formatting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
at System.Reflection.RuntimeAssembly.GetExportedTypes()
at System.Reflection.Assembly.get_ExportedTypes()
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 112
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembliesInDirectory(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 74
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 47
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectoryAsync(DirectoryInfo directory, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 317
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 164
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 42
```

I run `dotnet nuget disable source dotnetTools`; you'll go back to step three in the beginning.

**Comment by jonsequitur** [comment]
We moved `ISupportNuget` to a separate package which is why this error occurs if you're using the latest packages, that change hasn't been published to nuget.org yet, so I'm why you're seeing it.

In any case we'll be publishing these changes to nuget.org in the next couple of hours, so I expect that should resolve your issue.

**Comment by kkbruce** [comment]
@jonsequitur 

I have to apologize to you. In the most important step 4, I didn't choose the correct execution language for some reason, so I made a mistake in step 4 above. After the correction, it can be implemented correctly. Thank you for your help.

![image](https://user-images.githubusercontent.com/2024682/121636852-1b42f480-cabb-11eb-8abf-1829b8f879a9.png)

I have other questions. I'll open another issue to discuss with you.
