### ISSUE TITLE
CosmosClient in local Notebook throws exceptions

### ISSUE THREAD

**Issue by bryanrcarlson** [dotnet/interactive#14]
#### Describe the bug
Using Microsoft.Azure.Cosmos and CosmosClient throws "Unhandled Exception Could not load file or assembly 'Microsoft.Azure.Cosmos.Direct, Version=3.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified."

Code:

```
#r "nuget:Microsoft.Azure.Cosmos,3.5.1"

using Microsoft.Azure.Cosmos;

string uri = "https://myuri.documents.azure.com:443/";
string key = "ThisIsMadeUpAndThankYouForLookingAtThisIssueAETGPCjrVXat5KlIOaf2SxAxTzsujT4XyfZuEw==";

using (CosmosClient client = new CosmosClient(uri, key))
{
    
}
```

Adding a reference to Cosoms.Direct,
`#r "nuget:Microsoft.Azure.Cosmos.Direct,3.4.2"`

created a new error:

```
Unhandled Exception
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
   at Microsoft.Azure.Cosmos.DocumentClient.Initialize(Uri serviceEndpoint, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, IStoreClientFactory storeClientFactory)
   at Microsoft.Azure.Cosmos.DocumentClient..ctor(Uri serviceEndpoint, String authKeyOrResourceToken, EventHandler`1 sendingRequestEventArgs, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, JsonSerializerSettings serializerSettings, ApiType apitype, EventHandler`1 receivedResponseEventArgs, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, Func`2 transportClientHandlerFactory, IStoreClientFactory storeClientFactory)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, String authKeyOrResourceToken, CosmosClientOptions clientOptions)
   at Submission#18.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

Seems related to: [https://github.com/dotnet/try/issues/498](https://github.com/dotnet/try/issues/498)

I'm on dotnet-try --version: 1.0.19553.4+001b36724d769e844a53b22e3833a23caed3dc68

![image](https://user-images.githubusercontent.com/12533203/71211968-2b329d00-2265-11ea-80a1-62262e762db3.png)

Thanks

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other: 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge (new)
    - [ ] Safari

**Comment by KevinRansom** [comment]
We have reworked packagemanagement extensively.  This bug is fixed in the latest master branch.

![image](https://user-images.githubusercontent.com/5175830/78076073-927ae580-735a-11ea-8dfa-b72bb0e92bea.png)
