### ISSUE TITLE
F# Code with long string output caused display problem

### ISSUE THREAD

**Issue by ingted** [dotnet/interactive#1463]
### Describe the bug

```
#r @"nuget:FSharp.Data"
#r @"nuget:Http.fs"
#r "System.Xml.Linq.dll"
open FSharp.Data
open Hopac
open HttpFs.Client

let DailyTreasuryRealYieldCurveRate =
    Request.createUrl Get "https://data.treasury.gov/feed.svc/DailyTreasuryRealYieldCurveRateData"
    |> Request.responseAsString
    |> run

let DailyTreasuryYieldCurveRate =
    Request.createUrl Get "https://data.treasury.gov/feed.svc/DailyTreasuryYieldCurveRateData"
        |> Request.responseAsString
        |> run

type DailyTreasuryRealYieldCurveRateType = XmlProvider<Schema="G:\\DailyTreasuryRealYieldCurveRateData.xsd">

let DailyTreasuryRealYieldCurveRateData =
    DailyTreasuryRealYieldCurveRateType.Parse DailyTreasuryRealYieldCurveRate
```

![image](https://user-images.githubusercontent.com/4289161/124312484-fca7b900-dba1-11eb-9e50-42256b7f4c67.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** 
v1.0.2309030

- OS
    - Windows Server 2019
 - Browser 
    - Chrome
 - Frontend
    - Visual Studio Code

**Comment by jonsequitur** [comment]
It's not clear from the screen shot that this is a .NET Interactive-specific issue.

Can you provide DailyTreasuryRealYieldCurveRateData.xsd in order to repro?

**Comment by ingted** [comment]
[original page](https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=realyield)

[xsd link](https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Documents/DailyTreasuryRealYieldCurveRateData.xsd.zip)

**Comment by ingted** [comment]
Hi @jonsequitur , I pasted the url ^^

**Comment by psiLearn** [comment]
I ran into the same error, and created this simple repo: https://github.com/psiLearn/RexsTest the fsx files works as expected, the dib runs into error:
```
Error: System.ArgumentOutOfRangeException: The length cannot be greater than the capacity. (Parameter 'valueCount')
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.AppendHelper(String value)
   at System.IO.StringWriter.Write(String value)
   at Microsoft.DotNet.Interactive.Formatting.PocketView.Write(IReadOnlyList`1 args, FormatContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\PocketView.cs:line 208
....
```
