### ISSUE TITLE
#!connect mssql command fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by Pipsy100** [dotnet/interactive#1611]
Error: System.ArgumentException: Path to SQL Tools Service executable was not provided. (Parameter 'serviceExePath')
   at Microsoft.DotNet.Interactive.SqlServer.MsSqlServiceClient..ctor(String serviceExePath)
   at Microsoft.DotNet.Interactive.SqlServer.MsSqlKernelConnection.CreateKernelAsync(MsSqlConnectionOptions options, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass28_0`1.<<AddKernelConnection>b__0>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 364

**Comment by jonsequitur** [comment]
Can you provide more details to reproduce this?  

* Are you using VS Code or Jupyter? 
* What versions are you using? 
* What command did you run?

**Comment by Pipsy100** [comment]
I am using Version: 1.61.0-insider
Commit: 8d30d4d922dda917d22f05a81f2ab4fad7349779
Date: 2021-09-24T08:58:54.324Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-36-generic

I am using a .dib file. 
It throws the error when running the following command:

#!connect mssql --kernel-name dispite "Server=localhost;Database=dispite;User=SA;Password="";"

**Comment by jonsequitur** [comment]
Do you get the same result if you use non-Insiders VS Code?

**Comment by jonsequitur** [comment]
This looks like the same issue as #1602.
