### ISSUE TITLE
VS Code Online / Codespaces issues running javascript cells

### ISSUE THREAD

**Issue by zanecop** [dotnet/interactive#1613]
### Describe the bug
.net interactive notebooks fail to execute javascript cells when ran in a VS Code Online or GitHub CodeSpaces.  html cells with <script> tags work fine however...  Could only reproduce in codespaces environments, does not affect VS Code "IDE"

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

```
Version: 1.0.246201+da749355d416da20e634e5c80073b92356b57e0e
Build date: 2021-09-12T07:21:44.0000000Z
```

- OS
 - Ubuntu 20.04.3 LTS
 - Browser 
    - [X] Edge
 - Frontend
    - [X] VS Code Online/Codespaces

### Screenshots
Errors are related to the failed javascript cell.
![image](https://user-images.githubusercontent.com/15659043/134980975-f31af9f3-1be9-45f2-a8be-3922b511ae03.png)

**Comment by zanecop** [comment]
error content:

`workbench.web.api.js:71 [Extension Host] rejected promise not handled within 1 second: [object Object]
b @ workbench.web.api.js:71
$logExtensionHostMessage @ workbench.web.api.js:1484
_doInvokeHandler @ workbench.web.api.js:1484
_invokeHandler @ workbench.web.api.js:1484
_receiveRequest @ workbench.web.api.js:1484
_receiveOneMessage @ workbench.web.api.js:1484
(anonymous) @ workbench.web.api.js:1484
fire @ workbench.web.api.js:69
fire @ workbench.web.api.js:85
_receiveMessage @ workbench.web.api.js:85
(anonymous) @ workbench.web.api.js:85
fire @ workbench.web.api.js:69
acceptChunk @ workbench.web.api.js:85
(anonymous) @ workbench.web.api.js:85
(anonymous) @ workbench.web.api.js:609
invoke @ events.js:62
fire @ events.js:120
(anonymous) @ WebSocketFactory.ts:334
invoke @ events.js:62
fire @ events.js:120
handleDataReceived @ sshChannel.js:241
handleDataMessage @ connectionService.js:306
handleMessage @ connectionService.js:119
dispatchMessage @ sshSession.js:352
processMessages @ sshSession.js:279
async function (async)
processMessages @ sshSession.js:279
workbench.web.api.js:602   ERR Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText
   at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 45
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 261
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 57
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 72
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 162
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 42`

**Comment by jonsequitur** [comment]
This has been fixed in the latest release.
