### ISSUE TITLE
Imported nuget Package doesn't  its C++ dependency

### ISSUE THREAD

**Issue by romarro** [dotnet/interactive#1633]
### Describe the bug

I have tried to import the nuget package SharpFluids (https://www.nuget.org/packages/SharpFluids/). This package is a wrapper of another library implemented in C++ (CoolProp). The wrapping is done using swager.

The code is as follows:

cell:
#r "nuget: EngineeringUnits"
#r "nuget: SharpFluids"
#r "nuget: MathNet.Numerics"

cell:
using SharpFluids;
using EngineeringUnits;

cell:
var fldCald = new Fluid(FluidList.R134a);
fldCald.UpdatePH(Pressure.FromBars(5), SpecificEnergy.FromKilojoulesPerKilogram(180));

var fldRece = new Fluid(FluidList.R134a);
fldRece.UpdatePH(Pressure.FromBars(3), SpecificEnergy.FromKilojoulesPerKilogram(180));

Error las cell:
Error: System.TypeInitializationException: The type initializer for 'CoolPropPINVOKE64' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'CoolProp64' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at CoolPropPINVOKE64.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_CoolProp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at CoolPropPINVOKE64.SWIGExceptionHelper..cctor() in D:\a\1\s\SharpFluids\CoolPropFiles\CoolPropPINVOKE64.cs:line 114
   --- End of inner exception stack trace ---
   at CoolPropPINVOKE64.SWIGExceptionHelper..ctor()
   at CoolPropPINVOKE64..cctor() in D:\a\1\s\SharpFluids\CoolPropFiles\CoolPropPINVOKE64.cs:line 134
   --- End of inner exception stack trace ---
   at CoolPropPINVOKE64.AbstractState_factory__SWIG_0(String jarg1, String jarg2)
   at AbstractState.factory(String backend, String fluid_names) in D:\a\1\s\SharpFluids\CoolPropFiles\AbstractState.cs:line 52
   at SharpFluids.Fluid.SetNewMedia(MediaType Type) in D:\a\1\s\SharpFluids\SharpFluids files\Fluid.cs:line 448
   at SharpFluids.Fluid..ctor(MediaType Media) in D:\a\1\s\SharpFluids\SharpFluids files\Fluid.cs:line 56
   at SharpFluids.Fluid..ctor(FluidList Type) in D:\a\1\s\SharpFluids\SharpFluids files\Fluid.cs:line 64
   at Submission#7.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

it seems to me that the SharpFluid isn't capable of finding the dll.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

version 1.0.246201+da749355d416da20e634e5c80073b92356b57e0e
Build date: 2021-09-28T05:02:21.3948994Z

VS code:
Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [x ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
here is a screenshot of the package SharpFluids installation folder 
![net interactive issue](https://user-images.githubusercontent.com/7783693/136142733-662e7f74-47ba-498d-a53e-a645a98f2ee4.PNG)

**Comment by KevinRansom** [comment]
@romarro --- the package is not really authored correctly to contain native dependencies.  It works by running a build target that copies dependencies to an output directory.  dotnet interactive and the dotnet sdk supports packages with cross platform native dependencies.  The SharpFluids nuget package ... has only an implementation of the native dependency and a 64 bit version.  It is likely that the dependency will not load on all of windows/linux and macos.

You can find a description of how to package architecture specific libraries in a nuget package:  https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders

Please open a bug against the authors of SharpFluid to support cross platform packages, and at least layout the package so that Windows dependencies will be correctly probed.
