### ISSUE TITLE
PathToService cannot be null on a SQL Server

### ISSUE THREAD

**Issue by pipsy100** [dotnet/interactive#1682]
#!connect mssql --kernel-name dispiteKernel "Server=localhost;Database=dispite;User=SA;Password=";"

Error: System.InvalidOperationException: PathToService cannot be null or whitespace.
   at Microsoft.DotNet.Interactive.SqlServer.MsSqlKernelConnector.ConnectKernelAsync(KernelName kernelName)
   at Microsoft.DotNet.Interactive.SqlServer.ConnectMsSqlCommand.ConnectKernelAsync(KernelName kernelName, MsSqlKernelConnector connector, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass25_0`1.<<AddKernelConnection>b__0>d.MoveNext() in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 330
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 35
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 265
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 57
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 72
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 128
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\2\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 48

**Comment by colombod** [comment]
Do you have anymore details about version of the extension, vscode?

**Comment by jtbm37** [comment]
I am having the same issue with this version: Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.21559.2


VSCode:
```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.15.0-162-generic
```

Sql server docker image:
 "mcr.microsoft.com/mssql/server:2017-latest"
  "com.microsoft.product": "Microsoft SQL Server",
  "com.microsoft.version": "14.0.3162.1",
