### ISSUE TITLE
Can't Create a Custom Kernel Extension

### ISSUE THREAD

**Issue by JasonBock** [dotnet/interactive#1754]
**The package and version I'm asking about**: 
1.0.251301+06badd73c27d2c2065cf835ab7bd65bccd2339ee

### Question
I'm trying to create a custom extension, using the [ClockExtension](https://github.com/dotnet/interactive/tree/main/samples/extensions/ClockExtension) example as a guide. You can find my code [here](https://github.com/JasonBock/Collatz) - specifically, it's the `Collatz.Interactive` project. I created a notebook to test it out - `DemoExtension.ipynb`. When I run it....it finds the local NuGet package, but running the help command (`-h`) doesn't produce anything, and when I try to run it, I get this error:
```
Error: Required command was not provided.
Unrecognized command or argument '#!collatz'
Unrecognized command or argument '-s'
Unrecognized command or argument '444'
```
I'm not sure what I'm doing wrong. Any insight is appreciated - TIA.

**Comment by jonsequitur** [comment]
It looks like the thing you're missing is putting the extension .dll in this path within your package:

https://github.com/dotnet/interactive/blob/fd23041799a9e15d9ae4c55ef64c2d4e157fb774/samples/extensions/ClockExtension/ClockExtension.csproj#L22-L24

**Comment by JasonBock** [comment]
I tried that:
```
	<ItemGroup>
		<None Include="$(OutputPath)/Collatz.Interactive.dll" Pack="true" PackagePath="interactive-extensions/dotnet" />
	</ItemGroup>
```
But I get this error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU5100	The assembly 'interactive-extensions\dotnet\Collatz.Interactive.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.	Collatz.Interactive	C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	
```

**Comment by jonsequitur** [comment]
Putting it inside both folders will avoid this warning.

**Comment by JasonBock** [comment]
So I tried putting it into `lib`:
```
<None Include="$(OutputPath)/Collatz.Interactive.dll" Pack="true" PackagePath="lib" />
```
And now I get this error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU5101	The assembly 'lib\Collatz.Interactive.dll' is placed directly under 'lib' folder. It is recommended that assemblies be placed inside a framework-specific folder. Move it into a framework-specific folder.	Collatz.Interactive	C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	
```
Sorry, @jonsequitur, I really appreciate the responses, just not that familiar with these NuGet issues and I feel like I'm flailing a bit.

**Comment by JasonBock** [comment]
FWIW if I do this:
```
<None Include="$(OutputPath)/Collatz.Interactive.dll" Pack="true" PackagePath="lib\net5.0" />
```
Then I get this:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU5118	File 'C:\Users\jason\source\repos\Collatz\src\Collatz.Interactive\bin\Release\net5.0\Collatz.Interactive.dll' is not added because the package already contains file 'lib\net5.0\Collatz.Interactive.dll'	Collatz.Interactive	C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	
```

:|

**Comment by jonsequitur** [comment]
The ergonomics of this definitely need some work. But the pack process should just put it into the appropriate TFM-specific `lib` folder for you by default.

**Comment by JasonBock** [comment]
Agreed....just not sure why it thinks it isn't, though when I try to add it explicitly, then it thinks it's already there.

**Comment by jonsequitur** [comment]
I was able to get this to work by:
* turning off warnings as errors.
* adding these to the Collatz.Interactive.csproj:
```xml
		<OutputType>Library</OutputType>
		<IsPackable>true</IsPackable>
		<IncludeBuildOutput>true</IncludeBuildOutput>
        <PropertyGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE" Pack="true" PackagePath="" />
		<None Include="$(OutputPath)/Collatz.Interactive.dll" Pack="true" PackagePath="interactive-extensions/dotnet" />
	</ItemGroup>
```

![image](https://user-images.githubusercontent.com/547415/142043586-8891713a-767a-49bc-b7a1-8e58f2b9afa5.png)

**Comment by JasonBock** [comment]
Success!

...sort of.

So, I did what you suggested, and it now installs, and I get help on it, but...if I try to run it:
```
#!collatz -s 444
```
I get this error:
```
Error: System.InvalidOperationException: The type System.ReadOnlySpan`1[System.Byte] cannot be bound
   at System.CommandLine.Binding.ModelBinder.CreateInstanceInternal(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.Binding.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.Binding.ModelBinder.GetBestConstructorAndArgs(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.CreateInstanceInternal(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.Binding.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 34
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 256
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 57
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 72
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 144
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 42
```
I'm wondering if this has to do with the command wanting a `BigInteger` value and this is tripping things up for some reason. Not sure. At least the extension is installing, but I'm hoping this error is something that I can address!

**Comment by jonsequitur** [comment]
This error is because the parameter binding in System.CommandLine is making a best attempt at satisfying the `BigInteger` constructor but can't instantiate the `ReadOnlySpan<byte>`. You can probably solve this by providing a `ParseArgument<T>` delegate to your `Option<BigInteger>`.

**Comment by JasonBock** [comment]
I'll give that a whirl....

**Comment by JasonBock** [comment]
Finally! Success :)
![image](https://user-images.githubusercontent.com/904213/142052851-3a82e0a4-b7af-49f4-b925-4451d6327a34.png)
@jonsequitur thanks for the help.
