### ISSUE TITLE
Can't run BenchmarkDotNet inside .NET Interactive Notebook

### ISSUE THREAD

**Issue by obratim** [dotnet/interactive#1895]
Issue Type: <b>Bug</b>

Tried to run benchmark:

    BenchmarkRunner.Run

got error:

Error: System.IO.FileNotFoundException: Could not load file or assembly 'ℛ*2e295739-0d3e-430f-b26c-d1fd780c9897#1-68, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'ℛ*2e295739-0d3e-430f-b26c-d1fd780c9897#1-68, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at BenchmarkDotNet.Validators.JitOptimizationsValidator.Validate(ValidationParameters validationParameters)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Validate(BenchmarkRunInfo[] benchmarks, ILogger logger)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config, String[] args)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config, String[] args)
   at Submission#98.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

Extension version: 1.0.3103010
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:23:11.224Z)
OS version: Linux x64 5.15.16-calculate
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.65GB (4.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by obratim** [comment]
the notebook:
https://github.com/obratim/notebooks/blob/main/multithread%20random%20numbers.ipynb

**Comment by JonTheTurnip** [comment]
It would be really valuable if BenchmarkDotNet could run in a notebook.  It's something I'm trying to do at the moment.

**Comment by jonsequitur** [comment]
It would be very useful to be able to run benchmarks in a notebook. I think we'll need to build an extension for it. The issue you're hitting is that C# scripting emits an in-memory assembly for each code submission. BenchmarkDotNet doesn't know how to load those assemblies.

I've spent a little time trying to get this to work and came to the conclusion that without a change to BenchmarkDotNet, the simplest thing to do would be write a .NET Interactive extension that emits a project to disk. 

_Air code:_

<img width="762" alt="image" src="https://user-images.githubusercontent.com/547415/154813120-f316da61-2a0c-454e-947f-b7eab5592b09.png">

A few things this could do:

* Use the .NET Interactive middleware to grab the code submission and template it into a normal C# BenchmarkDotNet project
* Build and run that project 
* Store the benchmark runs as variables that could be shared with other kernels so you can use it programmatically e.g. for plotting

**Comment by JonTheTurnip** [comment]
@jonsequitur Thanks for the info.  To be honest I'm not familiar with inner workings of .net interactive or BenchmarkDotNet.  I'm going to chat with the rest of my team about this and I'll come back to you if I think that it's something that we can work on.
