### ISSUE TITLE
VS Code Interactive Notebook not working anymore: Could not load file or assembly 'System.Management.Automation'

### ISSUE THREAD

**Issue by stefan-schweiger** [dotnet/interactive#2088]
### Describe the bug
Since a few days .NET Interactive Notebooks haven't been working anymore for me in VS Code. It always just shows the spinner when I try to run something and doesn't do much besides it. The only thing that would come to mind which I've changed in the last week is installing .NET 6.0.6 (had 6.0.5 previously).

The diagnostic logs always show the following error:

```
Kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' started (76486).
kernel (76486) stderr: Unhandled exception: 
kernel (76486) stderr: System.BadImageFormatException: Could not load file or assembly 'System.Management.Automation, Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. An attempt was made to load a program with an incorrect format.

File name: 'System.Management.Automation, Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
   at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel..ctor()
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.CreateKernel(String defaultKernelName, FrontendEnvironment frontendEnvironment, StartupOptions startupOptions) in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 582
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__23>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 430
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__3>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 223
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.
kernel (76486) stderr: MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' ended (76486) with code 1.
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

I'm not able to run `#!about` since the notebooks aren't working at all for me, but the VS Code extension version is v1.0.3314010

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
Are there any pending VS Code updates? Making sure those are applied and then restarting VS Code sometimes solves these kinds of issues.

**Comment by stefan-schweiger** [comment]
@jonsequitur I'm currently on 1.68.1 (so most recent stable) and all extensions are up-to-date

**Comment by stefan-schweiger** [comment]
@jonsequitur yes I'm using a M1 Macbook Pro. I was on vacation last week and whatever the most recent version before that was didn't work. But after installing v1.0.3357010 today the notebooks seem to be working again. I don't know if there was an active effort to fix this issue but thank you anyway :)
