### ISSUE TITLE
Extension Completely Stopped Running Notebooks

### ISSUE THREAD

**Issue by Eddie-Hartman** [dotnet/interactive#2236]
### Describe the bug
Interactive notebooks have worked great for me in the past. At some point, whether due to an update, or some cause I'm unaware of, I cannot run notebooks at all anymore. What I mean by that is when I click to run, it will just run forever and nothing will happen. I can't use the display command, do simple addition, anything at all. Even the `#!about` magic command just hangs. I've tried updating Windows, VsCode, the Extensions, Uninstalling and re-installing the extensions, most of the general debugging steps.

I've not seen similar issues within the GitHub, so I'm guessing I'm somehow an isolated case, but I simply can't get this to work at all. Please advise.

My workflow is I'll typically want to test some small portion of code, so I'll put it into a new notebook, then run that. I use .ipynb extension with the .net kernel.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Even the about magic command doesn't run, but VsCode says 1.0.3405010

- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/14089997/187104712-94f164bb-a809-46a1-93ab-ad623c28e1da.png)

**Comment by Eddie-Hartman** [comment]
@jonsequitur That was enough info for me to figure out what I needed to do to fix it, though it may still be an open issue? You tell me what you think.

I didn't think to look at that output since I hide the bottom panel since typically my workflow doesn't depend on it. I'll keep that in mind in the future.

Here was the error:
```
Starting kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' using: dotnet tool run dotnet-interactive -- [vscode] stdio --working-dir c:\Users\EDDIEH~1\AppData\Local\Temp\git-difftool.a12908\left
Kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' started (1004).
kernel (1004) stderr: Unhandled exception: 
kernel (1004) stderr: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\Users\EddieHartman\AppData\Local\Temp\git-difftool.a12908\left'.
   at System.Environment.set_CurrentDirectoryCore(String value)
   at System.Environment.set_CurrentDirectory(String value)
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__19>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 365
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__3>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 222
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

So it seems like since the workspace folder that was open was from a git diff that I was done with and the files were gone, it was causing the kernel to not be created? I didn't have those files open though and was working from an unsaved new ipynb file, so I wouldn't have expected that to have been the issue, so IDK if this should turn into a bug ticket or not.

Either way, thanks for your help!

**Comment by jonsequitur** [comment]
That's a good find! Thanks for posting the logs. We'll open a separate issue for this.

**Comment by Eddie-Hartman** [comment]
Sounds good. Closing this then. Thanks for your help.

**Comment by jonsequitur** [comment]
You're welcome!
