### ISSUE TITLE
Unable to use Entity Framework

### ISSUE THREAD

**Issue by this-fifo** [dotnet/interactive#2359]
### Describe the bug
I am following the article steps listed here: https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/

Everything other than scaffolding a DbContext with --create-dbcontext and using Entity Framework works fine.

When attempting to use the kernel in a new cell I get an error saying it does not exist in the current context. — I am able to use SQL cells just fine with the #!sql-kernel magic, but the EF option in a C# environment does not seem to work.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version 1.0.350406 (See screenshot below for full details)

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code (Version 1.72.2)
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

<img width="1648" alt="Screen Shot 2022-10-18 at 8 50 20 AM" src="https://user-images.githubusercontent.com/6960701/196438000-4fb3a9a6-9dcb-47a5-bd36-3857de2d1a81.PNG">
<img width="1235" alt="Screen Shot 2022-10-18 at 8 52 55 AM" src="https://user-images.githubusercontent.com/6960701/196438014-5f9e6a4f-1e33-449a-838d-bad208f11a1a.PNG">
<img width="706" alt="Screen Shot 2022-10-18 at 9 03 09 AM" src="https://user-images.githubusercontent.com/6960701/196438032-d016b15f-e9ab-498c-847e-847dc9d9f6aa.PNG">

**Comment by this-fifo** [comment]
hey @jonsequitur, I appreciate the fast response and handling of this, but it does not seem like the package upgrade fixed my issue

I see that there has not been any new release in https://www.nuget.org/packages/Microsoft.DotNet.Interactive.SqlServer/#versions-body-tab

so I tried pointing to the https://pkgs.dev.azure.com/dnceng/ feed instead, which got me the following version using `*-*`

- Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.22518.1

unfortunately when attempting to use that version the error is even worse, the existing #!connect magic I was using in the second cell on my screenshot doesn't work at all, it gives me a:

```
Error: Required command was not provided.
Unrecognized command or argument 'mssql'.
Unrecognized command or argument '--create-dbcontext'.
Unrecognized command or argument '--kernel-name'.
Unrecognized command or argument 'local'.
Unrecognized command or argument '<connection string>'.
```

Can you please let me know what I am doing wrong and how should I be running this? Thank you!

**Comment by jonsequitur** [comment]
Did you try this in Insiders by any chance?

**Comment by jonsequitur** [comment]
Also, I think the build where this will show up is 1.0.0-beta.22518.2.

**Comment by this-fifo** [comment]
I did not try with insiders, I am now trying with 1.0.0-beta.22518.3 as well as 1.0.0-beta.22518.2

both give me the same error when running the connect sql magic function

I also noticed that when attempting to install the lib I sometimes get an error that says

```
Error: System.TypeLoadException: Could not load type 'Microsoft.DotNet.Interactive.Commands.SendValue'
 from assembly 'Microsoft.DotNet.Interactive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
at System.Reflection.RuntimeAssembly.GetExportedTypes()
at System.Reflection.Assembly.get_ExportedTypes()
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile,
 Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 112
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembliesInDirectory(DirectoryInfo
 directory, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 74
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo
 directory, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 47
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectoryAsync(DirectoryInfo directory,
 KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 308
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext
 context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 148
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext()
 in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 72
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext
 context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 44
```

the error seem to go away if I try reinstalling a couple times, but perhaps that is still silently failing

**Comment by this-fifo** [comment]
I don't know why, but I managed to have all things working now with the nuget version 1.0.0-beta.22504.6 by adding the following packages to my notebook:

```
#r "nuget: Microsoft.DotNet.Interactive.SqlServer, *-*"
#r "nuget: Microsoft.DotNet.Interactive.ExtensionLab, *-*"
#r "nuget: SandDance.InteractiveExtension, *-*"
#r "nuget: nteract.InteractiveExtension, *-*"
```

It seems that maybe some packages have implicit runtime dependencies? I've managed to have that working by accident while exploring other issues in the repo and learning about these other packages

**Comment by this-fifo** [comment]
Oh well, it seems it's an issue of kernel context getting switched without much attention on my behalf.

Apparently the `--create-dbcontext` option only applies if you run the #!connect magic from a C# (.NET Interactive) cell not the SQL (.NET Interactive)

It seems it had nothing to do with the packages, as I was able to now make it work successfully with just the default `.SqlServer` package as a dependency and using `.Display()` without any of the `ExploreWith` extensions.

Thank you so much for all your help and work on this so far, I'm learning a lot just by exploring this repository and playing around and it's been an absolute blast!
