### ISSUE TITLE
Problem Sharing Generics 

### ISSUE THREAD

**Issue by wpalacejackhenry** [dotnet/interactive#2370]
I am trying to leverage the strengths of PowerShell to fetch data and then leverage the strength of C#'s LINQ expressions to manipulate it. There seems to be an incompatibility when trying to pass a generic created in PowerShell to C#. Here is some simplified code to reproduce this error. The error seems to be occurring on the share magic command. 

#!powershell
class Weight {
    [string] $Category 
    [int] $Qty 
    [double] $Pct 
}

$jsonData = @'
{"Category":"A","Qty":4016,"Pct":0.007536462516},{"Category":"B","Qty":157203,"Pct":0.295008594870},{"Category":"C","Qty":7570,"Pct":0.014205931586},{"Category":"D","Qty":1119,"Pct":0.002099925686},{"Category":"E","Qty":362967,"Pct":0.681147208731},{"Category":"F","Qty":1,"Pct":0.000001876609}
'@

$weights = New-Object System.Collections.Generic.List[Weight]
$jsonData -split(',(?={)') | % {
    $w = New-Object Weight
    $w = [System.Text.Json.JsonSerializer]::Deserialize($_, [Weight])
    $weights.Add($w)
}
$weights   # display data

#!csharp
public class Weight {
    public string Category {get; set;}
    public int Qty {get; set;}
    public double Pct {get; set;}
}

#!share --from powershell weights

// Work with data using LINQ
//var ret = 
//from t in weights
//select t.Category;

The error message returned: 
Error: System.ArgumentException: Object of type 'System.Collections.Generic.List`1[Weight]' cannot be converted to type 'System.Collections.Generic.List`1[Submission#5+Weight]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at Microsoft.CodeAnalysis.Scripting.ScriptVariable.set_Value(Object value)
   at Microsoft.DotNet.Interactive.CSharp.CSharpKernel.SetValueAsync(String name, Object value, Type declaredType) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.CSharp\CSharpKernel.cs:line 182
   at Microsoft.DotNet.Interactive.KernelExtensions.DeclareValue(Kernel importingKernel, ValueProduced valueProduced, String declarationName, Boolean allowShareByRef) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelExtensions.cs:line 403
   at Microsoft.DotNet.Interactive.KernelExtensions.GetValueAndImportTo(Kernel fromKernel, Kernel toKernel, String fromName, String mimeType, String toName) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelExtensions.cs:line 359
   at Microsoft.DotNet.Interactive.KernelExtensions.<>c__DisplayClass12_0`1.<<UseValueSharing>b__2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelExtensions.cs:line 328
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext context)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 34
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 297
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 59
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 133
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 50

**Comment by wpalacejackhenry** [comment]
After reading through the documentation, I can see this is not currently supported. Although, it would be a nice feature enhancement. I was able to get around the limitation by using tuples instead of custom classes.

#!powershell
$jsonData = @'
{"Category":"A","Qty":4016,"Pct":0.007536462516},{"Category":"B","Qty":157203,"Pct":0.295008594870},{"Category":"C","Qty":7570,"Pct":0.014205931586},{"Category":"D","Qty":1119,"Pct":0.002099925686},{"Category":"E","Qty":362967,"Pct":0.681147208731},{"Category":"F","Qty":1,"Pct":0.000001876609}
'@

$weights = New-Object 'Collections.Generic.List[Tuple[string, int64, double]]'
$jsonData -split(',(?={)') | % {
    $weight = (($_ | ConvertFrom-Json))
    $weights.add([Tuple]::Create($weight.Category, $weight.Qty, $weight.Pct))
}
$weights

#!csharp
#!share --from powershell weights

// Work with data using LINQ
var ret = 
    from t in weights
    select (t.Item1, t.Item2);
ret // display results
