### ISSUE TITLE
Assembly load error when running C# cmdlet 

### ISSUE THREAD

**Issue by thomas-t1** [dotnet/interactive#243]
#### Describe the bug

After importing custom PS module in Jupyter PowerShell notebook, an error occurs when running a cmdlet from the module. When running in "plain" powershell 7 (GA) it works as expected. I.e. the failing assembly is located in the same directory as the PS module assembly.

```
Import-Module "c:\Novelda\<snip_path>\Novelda.DataTwister.PowerShell.dll"
```

```
try
{
    Get-TwisterInventory
}
catch
{
    Out-Host $_.Exception.ToString()

}
```
Out-Host: 
Line |
   7 |      Out-Host $_.Exception.ToString()
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A positional parameter cannot be found that accepts argument 'System.TypeInitializationException: The type initializer for 'Novelda.ServiceLocator' threw an exception.
 ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
File name: 'Microsoft.Extensions.DependencyInjection, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at Novelda.ServiceLocator..cctor()
   --- End of inner exception stack trace ---
   at Novelda.ServiceLocator.get_Provider() in C:\Novelda\XeThru\Novelda.DataTwister\Novelda.DataTwister.Settings\Settings.cs:line 86
   at Novelda.DataTwister.PowerShell.GetTwisterInventoryCmd.BeginProcessing() in C:\Novelda\XeThru\Novelda.DataTwister\Novelda.DataTwister.PowerShell\GetTwisterInventoryCmd.cs:line 23
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()'.

Please provide as much information as you can.
Loading dependent assemblies behaves differently in dotnetinteractive vs powershell 7

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Safari
 - Frontend
    - [x] Jupyter notebook
    - [ ] Jupyter lab
    - [ ] nteract

**Comment by daxian-dbw** [comment]
@thomas-t1 Your module depends on `Microsoft.Extensions.DependencyInjection`, is that assembly also in the module folder? PowerShell doesn't ship that assembly.

**Comment by thomas-t1** [comment]
Yes, the module folder contains all dependencies including the DI assembly, as I mentioned the module works as expected in "plain" powershell 7.0.0

**Comment by thomas-t1** [comment]
Not sure if it is relevant, but the error occurs inside a static constructor in the assembly that is dependent on `Microsoft.Extensions.DependencyInjection`

**Comment by daxian-dbw** [comment]
It turns out this is because the `3.1.1.0` version of `Microsoft.Extensions.DependencyInjection` is already loaded by the dotnet-interactive at its startup.
<img width="991" alt="Screen Shot 2020-03-11 at 4 07 22 PM" src="https://user-images.githubusercontent.com/127450/76472307-749d0f00-63b2-11ea-8f83-6acab4cf01d8.png">

I can update the version of the reference package in dotnet-interactive project, but the same project is bound to show up again until we finish the module isolation work in PowerShell.
