### ISSUE TITLE
Uncaught exception in ZMQStream callback

### ISSUE THREAD

**Issue by heaths** [dotnet/interactive#2485]
### Describe the bug
Using the latest `Microsoft.dotnet-interactive` from the `dnceng` feed on net7.0 I'm getting the following stack trace periodically. The notebook still mostly works, but the kernel frequently dies and restarts:

```
[W 2022-11-19 01:51:08.759 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7f0cc67d1930>
[E 2022-11-19 01:51:08.760 ServerApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 557, in _run_callback
        callback(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 279, in stream_callback
        return callback(self, msg)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 565, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_client/session.py", line 1060, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'301b0a3d3991cfb37ce8a6a4118fec25dd53ff18458a0e82740633dd25c8518e'
[E 2022-11-19 01:51:08.761 ServerApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 578, in _handle_events
        self._handle_recv()
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 607, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 557, in _run_callback
        callback(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 279, in stream_callback
        return callback(self, msg)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 565, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_client/session.py", line 1060, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'301b0a3d3991cfb37ce8a6a4118fec25dd53ff18458a0e82740633dd25c8518e'
```

Permalinks to relevant sources:
* [Dockerfile](https://github.com/heaths/azure-sdk-for-net-samples/blob/1ecb0b3387d5fd9f4ad5bf0e9919313f4bef5e43/Dockerfile)
* [Notebook](https://github.com/heaths/azure-sdk-for-net-samples/blob/1ecb0b3387d5fd9f4ad5bf0e9919313f4bef5e43/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples/Interactive.ipynb)

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ): 1.0.356808+613b88591c41a948f9f9ecb1a7ad76abb8aad229

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux (Please specify distro): Ubuntu 22.04
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [x] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by GilesBathgate** [comment]
I have the same problem, some of the errors show `tornado/ioloop.py` as the traceback root.

As below:

```
[E 2022-11-23 19:17:22.277 ServerApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f58f0fbb130>)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
        ret = callback()
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 662, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 578, in _handle_events
        self._handle_recv()
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 607, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 557, in _run_callback
        callback(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 279, in stream_callback
        return callback(self, msg)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 565, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_client/session.py", line 1060, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: ValueError: Invalid Signature: b'401b0a3d3991cfb37ce8a6a4118fec25dd53ff18458a0c82740633dd25c8518c'
```

**Comment by tschmidtsm** [comment]
I also have this problem, on Windows 10, Jupyter Lab (not with Conda, tried 3.5.0 and 3.4.7), and the latest stable of .NET Interactive (1.0.355307) - but older than the original post.

My workaround is to use .NET Interactive 1.0.350406.

Setup:

```
dotnet --version
# 6.0.403
dotnet tool list
# None listed
dotnet tool list --global
# None listed
dotnet tool install Microsoft.dotnet-interactive --global
# Tool 'microsoft.dotnet-interactive' (version '1.0.355307') was successfully installed.
py --version
# Python 3.10.8
py -m venv .venv
.\.venv\Scripts\Activate.ps1
pip install jupyterlab==3.5.0
get-command jupyter.exe | format-list
# The jupyter.exe in my virtual environment is listed
jupyter kernelspec list
# The built-in python3 kernel is listed
dotnet interactive jupyter install
# Installation messages for the 3 .NET kernels are listed
jupyter kernelspec list
# The 4 kernels are listed
jupyter lab
```

Problem:

Then I create a C# notebook. Before I run any cells,
within a few seconds, the console output shows both the
`Uncaught exception in ZMQStream callback` and
`Exception in callback functools.partial` traces mentioned above.

The kernel seems dead at this point, as it can't run:

```
var hello = "world";
hello
```

Sometimes, by shutting down/restarting kernels a few times, that cell will execute.

Once a kernel runs at least this cell, the notebook seems to be fine after that point - it remains responsive and there are no further stack traces.


___Workaround:___

```
dotnet tool uninstall Microsoft.dotnet-interactive --global
# Tool 'microsoft.dotnet-interactive' (version '1.0.355307') was successfully uninstalled.
dotnet tool install Microsoft.dotnet-interactive --global --version 1.0.350406
# Tool 'microsoft.dotnet-interactive' (version '1.0.350406') was successfully installed.
jupyter lab
```

Then the notebooks work fine.
