### ISSUE TITLE
Error during install Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.22553.7

### ISSUE THREAD

**Issue by codykonior** [dotnet/interactive#2487]
### Describe the bug
I have a fresh install of Azure Data Studio 1.4 on Windows 11 Pro x64. 

I have the latest .NET 6 SDK installed, as well as the Azure Data Studio extension ".NET 6 Runtime" (not sure if that's needed).

I install the ".NET Interactive Notebooks" extension.

I start a new notebook. I pick .NET Interactive as the kernel. I add a code cell of "C# (.NET Interactive)" with the contents:

```
#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"
```

I get this back:

```
Installed Packages
Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.22553.7
Error: System.TypeLoadException: Could not load type 'Microsoft.DotNet.Interactive.Commands.SendValue' from assembly 'Microsoft.DotNet.Interactive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 112
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembliesInDirectory(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 74
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 47
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectoryAsync(DirectoryInfo directory, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 308
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 148
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 72
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 44
```

If I restart ADS, it will give another error:

```
Kernel '.net-csharp' was not found. The default kernel will be used instead.
```

After that I can't select .NET Interactive from the Kernel drop-down lists anymore. I have to uninstall the extension, reload, and install it again. Then I can run a C#-only notebook, but, as soon as I restart I'll also get this error again too.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

```
Version: 1.0.350406+612aa40cba7d6a1f734272f71657a65561394752
Library version: 1.0.0-beta.22504.6+612aa40cba7d6a1f734272f71657a65561394752
Build date: 2022-11-21T10:34:18.1629180Z
```

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [X] Azure Data Studio

**Comment by brettfo** [comment]
The version of the extension in Azure Data Studio isn't on the latest bits, and using a package version of `*-*` always pulls in the highest version, so when referencing the SQL packages you'll have to match the version of the library, so in this case you'll need to type:

```
#r "nuget: Microsoft.DotNet.Interactive.SqlServer, 1.0.0-beta.22504.6"
```

**Comment by codykonior** [comment]
Wow that works thanks. How could I find that version number myself next time it updates?

**Comment by codykonior** [comment]
Ah thanks I see now. This works great!
