### ISSUE TITLE
Implement `RequestValue` in KQL kernel

### ISSUE THREAD

**Issue by 2BitSalute** [dotnet/interactive#2632]
**Is your feature request related to a problem? Please describe.**

I would like to be able to get values from a KQL cell into C# or F# cells for further processing.
Right now, when I try to `#!share --from kql cpu` (where `cpu` is a table-valued variable in the KQL cell above), I get the following exception:

```
Error: System.InvalidOperationException: Kernel Microsoft.DotNet.Interactive.KqlDiscoverabilityKernel: kql (kernel://pid-80572/kql) does not support command RequestValue
   at Microsoft.DotNet.Interactive.KernelExtensions.GetValueAndSendTo(Kernel fromKernel, Kernel toKernel, String fromName, String requestedMimeType, String toName) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelExtensions.cs:line 300
   at Microsoft.DotNet.Interactive.KernelExtensions.<>c__DisplayClass8_0`1.<<UseValueSharing>b__2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelExtensions.cs:line 272
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext context)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 34
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 326
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 150
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 77
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 51
```

**Describe the solution you'd like**
Ideally, I would be able to get a KQL table in the form of a data frame, though I don't know what particular library you'd be using for that. Alternatively, it could be exported in the shape that could be used to initialize a DataFrame (CSV?)

**Describe alternatives you've considered**
Azure Data Explorer client-side export could be an alternative, should it be implemented as a magic command (again, saving tabular data to a file, for example) -  https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/#client-side-export

**Comment by jonsequitur** [comment]
When you connect to a KQL kernel using `#!connect` you give the kernel a name using the `--kernel-name` option. That name, not `kql`, is the name you should use with `#!share`.

You can see more details here. KQL and SQL work the same way.

https://github.com/dotnet/interactive/blob/main/docs/working-with-data.md
