### ISSUE TITLE
Command cancellation leaks implementation details in the message we print out

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/interactive#2751]
### Describe the bug
I'd expect cancelling a cell to print out something like this in the output - "Command Cancelled"

Instead I get this: 
```
Error: System.OperationCanceledException: Command :SubmitCode: using System.Threading.Tasks;
using Microsoft.DotN ... cancelled.
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/18014426/219802695-c6a5bfba-1aed-4fab-99eb-c78686988202.png)

**Comment by AbhitejJohn** [comment]
In the same vein, here's what I see when I cancel user input :
```
Error: Input request cancelled

Error: Input request cancelled

Error: System.AggregateException: One or more errors occurred. (Input request cancelled)
 ---> System.Exception: Input request cancelled
   at Microsoft.DotNet.Interactive.Kernel.GetInputAsync(String prompt, Boolean isPassword, String typeHint) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.Static.cs:line 62
   at Microsoft.DotNet.Interactive.Kernel.GetInputAsync(String prompt, String typeHint) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.Static.cs:line 44
   at Microsoft.FSharp.Control.TaskBuilderExtensions.HighPriority.cont@405-8.Invoke(ResumableStateMachine`1& sm) in D:\a\_work\1\s\src\FSharp.Core\tasks.fs:line 406
   at <StartupCode$FSharp-Core>.$Tasks.resumptionInfo@171.MoveNext(ResumableStateMachine`1& sm) in D:\a\_work\1\s\src\FSharp.Core\tasks.fs:line 177
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at <StartupCode$FSI_0008>.$FSI_0008.main@()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) 
```
