### ISSUE TITLE
Nupkg does not work correctly on 'AnyCPU' platform

### ISSUE THREAD

**Issue by jmarrec** [dotnet/interactive#3008]
### Describe the bug

I'm not sure if it's really a bug or a problem between the keyboard and chair (there's a good chance it's the latter, I have very limited exposure to C#). **I guess perhaps I'm trying to find a way to specify the `Platform` when importing a .nupkg**?

I built a `.nupkg` locally, on the same machine I'm trying to use it on (Ubuntu 20.04 x64, dotnet 7.0.302)

```python
In [1]: #i "nuget:/media/DataExt4/Software/Others/OS-build-csharp/Products/csharp/Release"
Restore sources
    /media/DataExt4/Software/Others/OS-build-csharp/Products/csharp/Release

In [2]: #r "nuget:OpenStudio"
Restore sources

    /media/DataExt4/Software/Others/OS-build-csharp/Products/csharp/Release

/home/julien/.nuget/packages/openstudio/3.7.0/build/OpenStudio.targets(5,5): error : OpenStudio does not work correctly on 'AnyCPU' platform. You need to specify platform (x64). [/home/julien/.packagemanagement/nuget/Projects/118184--db243cc5-f863-4c64-9c90-b8386dfeaea5/Project.fsproj]
```
----

I can't seem to figure out why this happens and how to tell it I has the right platform. 

I thought x64 would be detected correctly.

```python
In [3]: #r "nuget:Microsoft.DotNet.PlatformAbstractions, 3.1.3"
         Console.WriteLine("{0}", Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier())

Restore sources

    /media/DataExt4/Software/Others/OS-build-csharp/Products/csharp/Release

Installed Packages

    Microsoft.DotNet.PlatformAbstractions, 3.1.3

ubuntu.20.04-x64
```

---

If I actually extract the .nupkg via this

```shell
mkdir Products/csharp/Release/extracted
cp Products/csharp/Release/OpenStudio*.nupkg Products/csharp/Release/extracted/
cd Products/csharp/Release/extracted/ && 7z e OpenStudio*.nupkg
```

and use this:

```python
In [4]: #r "/media/DataExt4/Software/Others/OS-build-csharp/Products/csharp/Release/extracted/OpenStudio.dll"
```

then everything works?!

----

I've also tried getting a version directly from nuget.org: https://www.nuget.org/packages/NREL.OpenStudio.linux-x64

```
In [5]: #r "nuget:NREL.OpenStudio.linux-x64, 3.5.1"
       using OpenStudio;
      OpenStudio.Model model = new OpenStudio.Model();
```

but the error is super weird, looks like it's appending a .so to a .so, looking for libname.so.so instead of libname.so? not sure.

<details>

<summary>Click to expand error log</summary>

```
System.TypeInitializationException: The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libopenstudio_model_csharp.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/julien/.dotnet/tools/.store/microsoft.dotnet-interactive/1.0.425803/microsoft.dotnet-interactive/1.0.425803/tools/net7.0/any/runtimes/linux-x64/native/libopenstudio_model_csharp.so.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libopenstudio_model_csharp.so.so: cannot open shared object file: No such file or directory
/home/julien/.nuget/packages/nrel.openstudio.linux-x64/3.5.1/lib/netstandard2.0/libopenstudio_model_csharp.so.so: cannot open shared object file: No such file or directory
/home/julien/.dotnet/tools/.store/microsoft.dotnet-interactive/1.0.425803/microsoft.dotnet-interactive/1.0.425803/tools/net7.0/any/runtimes/linux-x64/native/liblibopenstudio_model_csharp.so.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/liblibopenstudio_model_csharp.so.so: cannot open shared object file: No such file or directory
/home/julien/.nuget/packages/nrel.openstudio.linux-x64/3.5.1/lib/netstandard2.0/liblibopenstudio_model_csharp.so.so: cannot open shared object file: No such file or directory
/home/julien/.dotnet/tools/.store/microsoft.dotnet-interactive/1.0.425803/microsoft.dotnet-interactive/1.0.425803/tools/net7.0/any/runtimes/linux-x64/native/libopenstudio_model_csharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libopenstudio_model_csharp.so: cannot open shared object file: No such file or directory
/home/julien/.nuget/packages/nrel.openstudio.linux-x64/3.5.1/lib/netstandard2.0/libopenstudio_model_csharp.so: cannot open shared object file: No such file or directory
/home/julien/.dotnet/tools/.store/microsoft.dotnet-interactive/1.0.425803/microsoft.dotnet-interactive/1.0.425803/tools/net7.0/any/runtimes/linux-x64/native/liblibopenstudio_model_csharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/liblibopenstudio_model_csharp.so: cannot open shared object file: No such file or directory
/home/julien/.nuget/packages/nrel.openstudio.linux-x64/3.5.1/lib/netstandard2.0/liblibopenstudio_model_csharp.so: cannot open shared object file: No such file or directory

   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_OpenStudioModelCore(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper..ctor()
   at OpenStudio.OpenStudioModelCorePINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OpenStudio.OpenStudioModelCorePINVOKE.new_Model__SWIG_0()
   at OpenStudio.Model..ctor()
   at Submission#3.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at OpenStudio.OpenStudioModelCorePINVOKE.new_Model__SWIG_0()
   at OpenStudio.Model..ctor()
   at Submission#3.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

</details>

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [x] Linux: Ubuntu 20.04 x64
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment]
This should typically do the right thing:

```
#r "nuget:NREL.OpenStudio.linux-x64, 3.5.1"
```

NuGet should figure out which platform-specific DLLs to load.

**_But_** sometimes specific packages have quirks. 

@KevinRansom, does anything here stand out for you?
