### ISSUE TITLE
```#!connect jupyter --kernel-name pythonkernel --kernel-spec python3``` doesn't pick up on systems where python interpreter it is called "python3"

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/interactive#3063]
### Describe the bug

When I try to use:
```#!connect jupyter --kernel-name pythonkernel --kernel-spec python3```

I'm getting this stacktrace

```Error: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'python' with working directory '/Users/gauthiersegay/dev/src/github.com/fable-compiler/fable'. No such file or directory
at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
at Microsoft.DotNet.Interactive.Utility.CommandLine.StartProcess(String command, String args, DirectoryInfo workingDir, Action`1 output, Action`1 error, ValueTuple`2[] environmentVariables) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Utility\CommandLine.cs:line 173
at Microsoft.DotNet.Interactive.Jupyter.ZMQ.JupyterConnection.CreateKernelProcess(KernelSpec spec, String connectionFilePath) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Jupyter\ZMQ\JupyterConnection.cs:line 127
at Microsoft.DotNet.Interactive.Jupyter.ZMQ.JupyterConnection.CreateKernelConnectionAsync(String kernelSpecName) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Jupyter\ZMQ\JupyterConnection.cs:line 91
at Microsoft.DotNet.Interactive.Jupyter.JupyterKernelConnector.CreateKernelAsync(String kernelName) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Jupyter\JupyterKernelConnector.cs:line 28
at Microsoft.DotNet.Interactive.Jupyter.ConnectJupyterKernelCommand.ConnectKernelsAsync(KernelInvocationContext context, InvocationContext commandLineContext) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.Jupyter\ConnectJupyterKernelCommand.cs:line 72
at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass21_0.<<AddKernelConnector>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 271
--- End of stack trace from previous location ---
at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext context)
at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 33
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 326
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 41
```

I can probably work around this by altering my environment, but I'm wondering if the code who interprets this command could try `python3` if `python` doesn't work?

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [x] macOS
 - Frontend
    - [x] Visual Studio Code

**Comment by smoothdeveloper** [comment]
If my suggestion is ok, I'll try to get this working in a PR.

**Comment by jonsequitur** [comment]
@shibbas Should this just be a lookup against an existing kernelspec? I'm not sure I understand what's happening here.

**Comment by smoothdeveloper** [comment]
I tried a bit (just a bit) to get into the toolchain, but it felt complex to do end to end integration for adjusting what I was looking at; even if the developer documentation is actually pretty good, to explain how to setup the extension in vscode to point to new binaries, or how to deploy the typescript VS extension.

I wonder if some "smoke-test" projects that are easy to debug, in form of command line test projects would help.

I've dealt a bit with Fable codebase (which is also not trivial in terms of integrating with tooling of various ecosystems, etc.) and really liked the approach they use for "quicktest" targets, that makes it easy to focus on specific areas, even for newbie contributors (like me).

https://github.com/fable-compiler/Fable/blob/7311b48f58fa8b83d99a8b7d878e6e6c4266f23a/build.fsx#L834-L836

Using this in fable, I was able to get running in stepping into rust target, hack a bit the compiler code, and see how it affects the quicktest related code, knowing absolutely nothing of that codebase.

If there is a way to run a command line that basically makes the kernel submission to the python kernel, and stepping in the C# codebase, and would watch changes to recompile / run again, it would make the development loop easier.

I believe efforts put into this will increase community involvement.
