### ISSUE TITLE
Stuck on installing .Net interactive 

### ISSUE THREAD

**Issue by flerxu** [dotnet/interactive#3233]
Type: <b>Bug</b>

1.   Install  C# Dev Kit  and Polyglot notebooks extension;
2.  Open command center,  select "Ployglot :Create new blank notebook";
3.  Error dialog appears:
``` 
Command 'Ployglot Notebook: Create new blank notebook  ' resulted in an error ,
command 'polyglot-notebook.newNotebookNoDefaults' not found
```

Extension Log:
```
Extension started for VS Code Stable.
tool-uninstall: Executing [dotnet tool uninstall Microsoft.dotnet-interactive] in 'c:\Users\player\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode'.
tool-uninstall: Finished with code 0.
tool-uninstall: STDOUT:
Tool 'microsoft.dotnet-interactive' was successfully uninstalled and removed from manifest file c:\Users\player\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode\.config\dotnet-tools.json.
tool-install: Executing [dotnet tool install --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json --ignore-failed-sources Microsoft.dotnet-interactive --version 1.0.446104] in 'c:\Users\player\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode'.
tool-install: Finished with code 1.
tool-install: STDERR:
Unhandled exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\player\.dotnet\toolResolverCache\1\microsoft.dotnet-interactive' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.Save(IDictionary`2 restoredCommandMap)
   at Microsoft.DotNet.Tools.Tool.Install.LocalToolsResolverCacheExtensions.SaveToolPackage(ILocalToolsResolverCache localToolsResolverCache, IToolPackage toolDownloadedPackage, String targetFrameworkToInstall)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.Install(FilePath manifestFile)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
Error acquiring dotnet-interactive tool: undefined
```

Modes:
<details>
<summary>Extension list </summary>

- GitHub.github-vscode-theme
- ms-dotnettools.csdevkit
- ms-dotnettools.csharp
- ms-dotnettools.dotnet-interactive-vscode
- ms-dotnettools.vscode-dotnet-runtime
- ms-dotnettools.vscodeintellicode-csharp
- ms-python.python
- ms-python.vscode-pylance
- ms-toolsai.jupyter
- ms-toolsai.jupyter-keymap
- ms-toolsai.jupyter-renderers
- ms-toolsai.vscode-jupyter-cell-tags
- ms-toolsai.vscode-jupyter-slideshow
- ms-vscode.Theme-MaterialKit
- SumitSaha.learn-with-sumit-theme

</details>

<details>
<summary>App and Extension Info</summary>

dotNet Interactive extension version: 1.0.4461040
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (10.13GB free)|
|Process Argv|--crash-reporter-id 62384e17-f9d1-4d78-b095-6b26fa04322a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmhint1:30842940
dsvsc015:30845448

```

</details>

**Comment by gmartinka** [comment]
I am seeing this as well. Its happening in both Cod and Code Insiders. I have tried uninstalling and reinstalling both the polyglot extension and all of VS Code.  Notebooks that used to work no longer work,

This is the error I am getting when trying to open a notebook that used to work. 

`Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\809cf8e8-bb66-40e7-bd29-f3394060f9d1"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 8:50:51 PM] [Program] Language server initialized
[Error - 8:50:51 PM] [LanguageServerHost] System.InvalidOperationException: didOpen received for vscode-notebook-cell:/c:/source/local machine configuration/datacenter/tst_ads_sql_notebook.ipynb#W1sZmlsZQ== which is already open. - line 106
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.StartTrackingAsync(Uri uri, SourceText documentText, String languageId, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs:line 106
   at Microsoft.CodeAnalysis.LanguageServer.Handler.DocumentChanges.DidOpenHandler.HandleNotificationAsync(DidOpenTextDocumentParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs:line 42
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
[Error - 8:50:51 PM] [LanguageServerHost] System.InvalidOperationException: didOpen received for vscode-notebook-cell:/c:/source/local machine configuration/datacenter/tst_ads_sql_notebook.ipynb#W1sZmlsZQ== which is already open. - line 106
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.StartTrackingAsync(Uri uri, SourceText documentText, String languageId, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs:line 106
   at Microsoft.CodeAnalysis.LanguageServer.Handler.DocumentChanges.DidOpenHandler.HandleNotificationAsync(DidOpenTextDocumentParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs:line 42
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync() in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 239
[Info  - 8:50:51 PM] Error processing queue, shutting down
[Error - 8:50:51 PM] Workspace diagnostic pull failed.
Canceled: Canceled
	at s.handleFailedRequest (c:\Users\gmartin2\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\dist\extension.js:2:2316987)
	at c:\Users\gmartin2\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\dist\extension.js:2:2354399
	at async g.pullWorkspaceAsync (c:\Users\gmartin2\.vscode\extensions\ms-dotnettools.csharp-2.7.25-win32-x64\dist\extension.js:2:2351707)
[Error - 8:50:51 PM] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

**Comment by gmartinka** [comment]
After running `dotnet tool update --global Microsoft.dotnet-interactive` and restarting Code, my notebooks are working again! 

I guess there must have been a problem with updating via Code, I don't know why though.

**Comment by flerxu** [comment]
> After running `dotnet tool update --global Microsoft.dotnet-interactive` and restarting Code, my notebooks are working again!
> 
> I guess there must have been a problem with updating via Code, I don't know why though.

I have tried everything but none worked. After reinstalling Windows 11 , it worked.

**Comment by jonsequitur** [comment]
@BrianL-STCU Your VS Code install looks to be somewhat out of date. Are you able to update to the latest VS Code and Polyglot Notebooks extension versions, and install the .NET 8 SDK?

**Comment by BrianL-STCU** [comment]
@jonsequitur keeping it up to date has become quite a hassle due to microsoft/winget-cli#3068. I didn't realize it had been two months already, but I got it updated, though unfortunately it hasn't helped.

<details><summary>VSCode details</summary>

```txt
Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z (2 days ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

</details>

**Comment by BrianL-STCU** [comment]
The Extension Host output shows:

```txt
2023-12-08 16:25:13.438 [error] Activating extension ms-dotnettools.dotnet-interactive-vscode failed due to an error:
2023-12-08 16:25:13.438 [error] TypeError: Cannot read properties of undefined (reading 'workingDirectory')
	at c:\Users\█████████\.vscode\extensions\ms-dotnettools.dotnet-interactive-vscode-1.0.4606020\out\src\vscode-common\extension.js:238:140
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\█████████\.vscode\extensions\ms-dotnettools.dotnet-interactive-vscode-1.0.4606020\out\src\vscode-common\extension.js:7:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by BrianL-STCU** [comment]
Our decrypting firewall may be causing an issue with the download. Is there a way to manually install .NET Interactive in VSCode, since the automated step doesn't seem reliable in our environment? Or to reference the system installation which is already there?

**Comment by BrianL-STCU** [comment]
The version it's trying to download has been updated, but it still never completes:

![Installing .NET Interactive version 1.0.460602](https://github.com/dotnet/interactive/assets/20843057/e237ae05-cfcc-467d-8531-49699bcbe10c)

**Comment by BrianL-STCU** [comment]
I think I may have correlated the problem with our firewall. I'll report back if that turns out to be the problem. It could be that the download URL is very triggering to certain enterprise security.

**Comment by BrianL-STCU** [comment]
Confirmed that was the problem.

**Comment by Puiu** [comment]
I was having the same problem when VS Code tried to install dotnet-interactive. I then tried to install the tool using dotnet tool install command but got this error:

**_"Package Source Mapping is enabled, but no source found under the specified package ID: microsoft.dotnet-interactive. See the documentation for Package Source Mapping at https://aka.ms/nuget-package-source-mapping for more details."_**

I then looked for nuget.config on my PC and when i opened it I noticed that my file looked like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSourceMapping>
    <packageSource key="company-internal-packages">
        <package pattern="Polly" />
      </packageSource>
    <packageSource key="nuget.org">
      <package pattern="Microsoft.Extensions.Http.Polly" />
      <package pattern="Polly.Core" />
      <package pattern="Microsoft.Extensions.Diagnostics.Abstractions" />
      <package pattern="OpenTelemetry.Api.ProviderBuilderExtensions" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```

I don't know exactly why the file looked like this, but after changing the contents of the nuget package source to this, the dotnet tool managed to install the tool:

```
<packageSource key="nuget.org">
      <package pattern="Microsoft.*" />
    </packageSource>
```

**Comment by worthapenny** [comment]
... similar issue:

![Image](https://github.com/user-attachments/assets/3b2e4ebf-95c0-448f-ba9b-12ee80ea0a8f)

I already have .NET 8.0 SDK
used to work fine
something recently changed and can't get it to work

```ps1
PS C:\My\Path> dotnet tool update --global Microsoft.dotnet-interactive
Tool 'microsoft.dotnet-interactive' failed to update due to the following:
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'microsoft.dotnet-interactive' failed to install. Contact the tool author for assistance.
```

My C:\Users\<username>\AppData\Roaming\NuGet\NuGet.Config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

**Comment by jonsequitur** [comment]
@worthapenny The latest release requires .NET 9.

**Comment by worthapenny** [comment]
> [@worthapenny](https://github.com/worthapenny) The latest release requires .NET 9.

✅ Confirmed Fixed. Installing the .NET 9 resolved the issue.

> Download the .NET 9 from: 
> https://dotnet.microsoft.com/en-us/download/dotnet/9.0

**Comment by kamend** [comment]
I can confirm, installing .NET 9 fixed it for me too.

**Comment by jhamilton09** [comment]
I started off with .NET 9 installed, launched VS Code, and was getting stuck on "installing .net interactive" when creating my first notebook. My solution was to go to the extension's settings and change the Dotnet-interactive: Interactive Tool Source setting to https://api.nuget.org/v3/index.json
After restarting VS Code, I created a new notebook and it successfully installed .net interactive and opened the notebook.

**Comment by GF-Huang** [comment]
Issue still.

```
Installing .NET Interactive version 1.0.632301...
```

Polyglot Notebooks `1.0.6323010`

VSCode
```
版本: 1.103.0 (user setup)
提交: e3550cfac4b63ca4eafca7b601f0d2885817fd1f
日期: 2025-08-06T21:40:10.271Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Windows_NT x64 10.0.26100
```

.NET
```
C:\Users\xxx>dotnet --list-sdks
9.0.302 [C:\Program Files\dotnet\sdk]

C:\Users\xxx>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by matthewturner** [comment]
> The Extension Host output shows:
> 
> 2023-12-08 16:25:13.438 [error] Activating extension ms-dotnettools.dotnet-interactive-vscode failed due to an error:
> 2023-12-08 16:25:13.438 [error] TypeError: Cannot read properties of undefined (reading 'workingDirectory')
> 	at c:\Users\█████████\.vscode\extensions\ms-dotnettools.dotnet-interactive-vscode-1.0.4606020\out\src\vscode-common\extension.js:238:140
> 	at Generator.next (<anonymous>)
> 	at fulfilled (c:\Users\█████████\.vscode\extensions\ms-dotnettools.dotnet-interactive-vscode-1.0.4606020\out\src\vscode-common\extension.js:7:58)
> 	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I had this `workingDirectory` issue and found that I had installed .NET 10 SDK. I installed the .NET 9 SDK and it started working.

**Comment by jonsequitur** [comment]
This typically happens when new versions of .NET are released. Because .NET Interactive requires a specific SDK version, and because the install requires .NET, it won't install correctly unless the .NET version matches the currently-required .NET Interactive version.
