### ISSUE TITLE
No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText with target kernel '.NET'

### ISSUE THREAD

**Issue by MikeCheel** [dotnet/interactive#3244]
### Describe the bug
1) Create a new polyglot notebook file (ipnyb).
2) Create a single cell (calue -Raw Value Storage) and insert the following code (csv file gotten from https://catalog.data.gov/dataset/lottery-powerball-winning-numbers-beginning-2010):

```
#!value --name csvdata --from-file "<my directory>\Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv"

#!js
#!set --name csvdata --value @value:csvdata

#!html
<iframe id="embedIframe" src="https://microsoft.github.io/SandDance/embed/v4/sanddance-embed.html" style="height:700px;width:100%"></iframe>

#!js
embedIframe = document.getElementById('embedIframe');
embedIframe.onload = () => {
    //ready to send commands to SandDance Embed    
    data = { rawText: csvdata, type: "csv"};
    props = { theme: 'dark-theme', initialSidebarClosed: true, initialRenderer: { advanced: true } };    
    embedIframe.contentWindow.postMessage({ action: 'load', data, props }, '*');    
}
```

3) Observe process that results in error in the title:

Error: Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText with target kernel '.NET'.
at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 183
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 324
at Microsoft.DotNet.Interactive.CompositeKernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 185
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.App.KernelExtensions.<>c__DisplayClass3_0.<<UseTelemetrySender>b__0>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\KernelExtensions.cs:line 134
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.App.KernelExtensionLoader.<>c__DisplayClass0_0.<<UseNuGetExtensions>b__0>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\KernelExtensionLoader.cs:line 39
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 77
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 77
--- End of stack trace from previous location ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 51

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [ ] Windows 11
    - [ x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [x ] Other (please specify) Polyglot Notebook

**Comment by jonsequitur** [comment]
Are you seeing this error in log output or did you see it in the notebook output cell? Can you provide a screen shot?

**Comment by MikeCheel** [comment]
When I open code and try to run the exact same notebook, I now get csvdata not found in kernal value. I keep varying error messages when I try to get this to run. I have actually gotten it to run but it is very hit or miss.

**Comment by MikeCheel** [comment]
> Are you seeing this error in log output or did you see it in the notebook output cell? Can you provide a screen shot?

I managed to finally get a screenshot: 
![image](https://github.com/dotnet/interactive/assets/2339881/23d719fc-7e23-4fd3-b672-16d81430d1da)

**Comment by ehoops-microsoft** [comment]
Hi I also get this with pwsh - PowerShell kernel

Using the workaround in this issue doesn't make the error appear: https://github.com/dotnet/interactive/issues/415

**Comment by eosfor** [comment]
it feels like when i start a cell, im my case in powershell and hover a mouse cursor over any text in that cell i get this

```
Error: Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText with target kernel 'pwsh'.
at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 183
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 324
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 51
```

![image](https://github.com/dotnet/interactive/assets/9363027/4d896f83-7414-4cfe-8cf3-a3adb8e8dfec)

**Comment by eosfor** [comment]
even though the magic command is there it still throws

![image](https://github.com/dotnet/interactive/assets/9363027/90fec3b0-f8b8-47eb-b45a-722eb8fe2da7)

**Comment by jonsequitur** [comment]
Thanks. It looks like this happens when hovering over code whose kernel doesn't support hover text while a code submission is currently running. The bug is that the `RequestHoverText` is getting parented under the `SubmitCode` command so its output is being displayed.

The underlying issue is #2336. I'll open another issue to track the mistaken parenting.

**Comment by ambrose-leung** [comment]
I'm still getting this error with the latest pre release and release versions.

For me, I have 5 #!import magic commands in one cell and if I hover over the cell while running (which happens mostly by accident), I get the error.

It's mildly frustrating because this error was not present in release version 1.0.4461040 (1 month ago) and was introduced in version 1.0.4509030 -  (I hope this may be helpful for the .NET interactive team find the bug)

I'm demoing a lot of stuff to my team with Polyglot notebooks, because everything else is amazing.  I'd like for others in my team to use it, but stuff like this doesn't instill confidence.

**Comment by lukemurraynz** [comment]
I'm getting this error as well: 

![image](https://github.com/dotnet/interactive/assets/24467442/452ce28f-8b4e-4747-9dff-d75c48858746)

Using the SDK 7, as 8 didn't seem to run at all in my devcontainer.

https://github.com/lukemurraynz/AzurePowerShellNotebook/blob/main/.devcontainer/devcontainer.json
