### ISSUE TITLE
PSInvalidOperationException: A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.

### ISSUE THREAD

**Issue by rasmuseeg** [dotnet/interactive#3266]
### Describe the bug
 * Created a new *.dib notebook
 * Add first new code cell with contents: 
```
#!pwsh
$files = 1..10;
$processedFiles = @()
foreach($file in $files)
{
    Write-Host "Processing file: file${file}.txt"
    Start-Sleep -Seconds 1
    $processedFiles += "file${file}.txt"
}
```
 * Add second new code cell with contents: 
```
#!pwsh
# Add command to pipeline queue
$processedFiles | ForEach-Object { Write-Host "Adding file to pipeline: $_"; Start-Sleep -Seconds 1; $_ } | Out-Null
```
 * Click the "Run All"  
 * When the first cell completes
 * The second cell shows an error, but finishes:
```
Error: System.Management.Automation.PSInvalidOperationException: A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.
at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndMarkSessionStateProxyCallInProgress()
at System.Management.Automation.Runspaces.RunspaceBase.get_InvokeProvider()
at System.Management.Automation.Runspaces.SessionStateProxy.get_InvokeProvider()
at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel.Microsoft.DotNet.Interactive.IKernelCommandHandler<Microsoft.DotNet.Interactive.Commands.RequestValueInfos>.HandleAsync(RequestValueInfos command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 175
at Microsoft.DotNet.Interactive.Kernel.<>c__DisplayClass82_0`1.<SetHandler>b__0(KernelCommand _, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 867
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 324
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 51
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
```
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.451402+c98f093c24bc8c2479e381d51e6c481ea48206a9
Library version: 1.0.0-beta.23514.2+c98f093c24bc8c2479e381d51e6c481ea48206a9
Build date: 2023-10-17T07:22:14.2772234Z
https://github.com/dotnet/interactive
```

- OS
    - [x] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [x] Other (please specify)
     - [x]  Polyglot Notebook Extension

### Screenshots
![Screenshot 2023-10-17 111554](https://github.com/dotnet/interactive/assets/1511208/83a09790-d721-45dc-b7ca-518a33ead27b)

**Comment by nullptrerror** [comment]
I have the same issue. I'm using the Polyglot Notebooks v1.0.4517010

My first job deletes the local git folder if it exists I tried making it a thread job to await for it but no luck.

**first job**:
```pwsh
$job = Start-ThreadJob -ScriptBlock {
    Write-Host "# 0. Delete the .git folder if it exists."
    $gitPathFolder = Join-Path -Path $PWD -ChildPath '.git';
    if (Test-Path -Path $gitPathFolder) {
        Remove-Item -Path $gitPathFolder -Recurse -Force -ErrorAction SilentlyContinue;
        Write-Host '# 0. The .git folder has been removed.'
    } else {
        Write-Host '# 0. The .git folder does not exist.'
    }
}
Wait-Job -Job $job | Out-Null
Receive-Job -Job $job
Remove-Job -Job $job
```
**second job**:
```pwsh
# 5. Initialize the git repository.
$job = Start-ThreadJob -ScriptBlock {
    Write-Host "# 5. Initialize the git repository."
    Write-Host "# 5."(git init);
}
Wait-Job -Job $job | Out-Null
Receive-Job -Job $job
Remove-Job -Job $job
```

![image](https://github.com/dotnet/interactive/assets/59756494/2e683684-f4d3-4a0f-b263-8ee5b7d7775e)
