### ISSUE TITLE
.NET Interactive is not working completely

### ISSUE THREAD

**Issue by heavenwing** [dotnet/interactive#3290]
### Describe the bug
repro steps:
- Create a .ipynb notebook file in VSCode with .NET Interactive
- Write very simple code ,like `var a="abc"` 
- I noticed that code don't have syntax highlight 
- Run this notebook, it stuck infinitely 

In Polyglot Notebooks diagnose windows, I got this continual error:
```
Process 'dotnet' with PID 10944 exited with code 1 and signal null
Started process 10644: dotnet tool run dotnet-interactive -- notebook-parser
process 10644 stderr: Run "dotnet tool restore" to make the "dotnet-interactive" command available.
``` 

Another problem is I cannot create .dib notebook file, after create it, nothing happen.

I tried re-install .NET Interactive dotnet tool and Polyglot Notebooks extension, don't resolve it.

However, after I install .NET Interactive into Jupyter Notebook as Jupyter kernel, it's working.

### Please complete the following:

1.0.451701+e231cd6f4a395b6f74568c5ad95a15cbecb85cf2

- OS
    - [x] Windows 11
 - Browser 
    - [x] Edge
 - Frontend
    - [x] Visual Studio Code

**Comment by jonsequitur** [comment]
@heavenwing, do you still see this issue after following the steps here?

https://github.com/dotnet/interactive/blob/main/docs/FAQ.md#troubleshooting

**Comment by heavenwing** [comment]
When I try to "Restart the current notebook's kernel", I got below error:

```log
2023-11-07 09:10:31.852 [info] [Info  - 9:10:31 AM] (13724) Pylance language server 2023.11.10 (pyright 088ebaa5) starting
2023-11-07 09:10:31.883 [info] [Info  - 9:10:31 AM] (13724) Server root directory: C:\Users\yoz\.vscode\extensions\ms-python.vscode-pylance-2023.11.10\dist
2023-11-07 09:10:31.948 [info] [Info  - 9:10:31 AM] (13724) Starting service instance "webapi-client"
2023-11-07 09:10:32.331 [info] [Info  - 9:10:32 AM] (13724) Setting pythonPath for service "webapi-client": "C:\Users\yoz\AppData\Local\miniconda3\python.exe"
2023-11-07 09:10:32.332 [info] [Info  - 9:10:32 AM] (13724) Setting environmentName for service "webapi-client": "3.11.5 (base conda)"
2023-11-07 09:10:33.804 [info] [Info  - 9:10:33 AM] (13724) Assuming Python version 3.11
2023-11-07 09:10:35.215 [info] [Info  - 9:10:35 AM] (13724) No source files found.
2023-11-07 09:10:37.551 [info] ERROR: The process "13204" not found.

2023-11-07 09:10:37.552 [info] [Error - 9:10:37 AM] Server process exited with code 1.
2023-11-07 09:10:37.554 [info] [Error - 9:10:37 AM] Connection to server got closed. Server will not be restarted.
2023-11-07 09:10:37.555 [info] [Error - 9:10:37 AM] Handling connection close failed
2023-11-07 09:10:37.555 [info] TypeError: e.clear is not a function
    at _.cleanUp (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2412859)
    at _.handleConnectionClosed (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2417283)
    at _.handleConnectionClosed (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2578252)
    at c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2416709
    at o.invoke (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
    at s.fire (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
    at te (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2349784)
    at o.invoke (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
    at s.fire (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
    at d.fireClose (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2372012)
    at ChildProcess.<anonymous> (c:\Users\yoz\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2384364)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
```

**Comment by heavenwing** [comment]
When I upgrade my .NET from 7.0 to 8.0, this problem is resolved.
