### ISSUE TITLE
No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText with target kernel 'pwsh'.

### ISSUE THREAD

**Issue by tymtam2** [dotnet/interactive#3307]
### Describe the bug

When hovering over a PowerShell code cell **when the cell is running** the error show just below is produced. The code seems to execute correctly. 

```
Error: Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText with target kernel 'pwsh'.
at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 184
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 330
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 41
```

### Example code

```
$lyrics = "I feel that you are changing me
I cannot decipher exactly what that means
Something about how that baby came
Let's meet in the summer, start over again"

Start-Sleep 3 # seconds, pause to appreciate how good the song is
```

### Workarounds

In order of preference:
1. Move away from PowerShell notebooks :P
2. Avoid helicopter parenting aka "Don't hover" 
3. Hover and don't worry about the error. 

The workarounds from https://github.com/dotnet/interactive/issues/415#issuecomment-629297230 don't seem to work. 

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

Version: 1.0.455704+c7327de6b8b72027889136cc14fe1325662c02a2

Library version: 1.0.0-beta.23557.4+c7327de6b8b72027889136cc14fe1325662c02a2

Build date: 2023-11-08T23:05:55.1801464Z

- OS
    - [X] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://github.com/dotnet/interactive/assets/1097613/d1e514a4-604a-4cc8-ac8b-439518dd6976)

**Comment by jonsequitur** [comment]
Thanks for the details. This is a duplicate of #3257, which is being worked on right now.
