### ISSUE TITLE
Polyglot Workbook never loads / stays blank

### ISSUE THREAD

**Issue by hesselmonk** [dotnet/interactive#3482]
### Describe the bug

Opening a previously working .dib workbook now results in an infinite loading bar at the top of the window and no output in the notebook (or any other) console.

### Details

`v1.0.5129010` (according to the plugin page in VSCode, which is strange because that tag doesn't seem to exist in this repo)

- OS
    - [x ] Windows 10
 - Frontend
    - [x] Visual Studio Code 

After reverting to previous versions it seems that it broke after `v1.0.5101020`.

### Screenshots

![image](https://github.com/dotnet/interactive/assets/28805623/c5e2fe47-1e14-4356-9918-9bd77173bd33)

**Comment by jonsequitur** [comment]
Do you have pending updates to VS Code or the Polyglot Notebooks extension? What versions are you using and what is the output of running `dotnet --info` in your console?

**Comment by IntegerMan** [comment]
@hesselmonk I'm curious if you see anything in VS Code's **Output** view with **Polyglot Notebook: diagnostics** selected. This has helped me  spot a few stranger issues in the past during installation.
![image](https://github.com/dotnet/interactive/assets/5049957/1e2c9a4b-7dc0-4a3b-bf07-d09fc835a697)

**Comment by hesselmonk** [comment]
Thanks, I looked in the console but completely missed the dropdown! (In my defence, it is kind of hidden in plain sight)

And it indefinitely outputs:

```
Process 'dotnet' with PID 20236 exited with code 3762504530 and signal null
Started process 7904: dotnet tool run dotnet-interactive -- notebook-parser
process 7904 stderr: Unhandled exception. 
process 7904 stderr: System.IO.FileNotFoundException: Could not load file or assembly 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at Microsoft.DotNet.Interactive.App.Program.<Main>(String[] args)
```

**Comment by jonsequitur** [comment]
That's a strange one. That assembly is part of the `dotnet-interactive` package.

Did you run `dotnet --info` in the same folder where the notebook is located?

**Comment by hesselmonk** [comment]
I ran `dotnet --info` from the embedded console, which might be a folder or two up from the actual notebook itself. Interestingly, when I checked just now it all seems to work, so _something_ in a recent (minor?) update has resolved the issue. I'll close it and add the most recent version info here in case someone wants to investigate still. 

polyglot notebook version: `v1.0.5164010`
dotnet install tool version: `v2.0.3`

vscode info:
```
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

dotnet info:
```
.NET SDK:
 Version:           8.0.103   
 Commit:            6a90b4b4bc
 Workload version:  8.0.100-manifests.4e94be9c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.103\

.NET workloads installed:
 Workload version: 8.0.100-manifests.4e94be9c
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  6.0.420 [C:\Program Files\dotnet\sdk]
  7.0.117 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.407 [C:\Program Files\dotnet\sdk]
  8.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by eosfor** [comment]
@jonsequitur same here. perhaps that is because I accidentally deleted smth, not sure

```console
xtension started for VS Code Stable.
tool-uninstall: Executing [dotnet tool uninstall Microsoft.dotnet-interactive] in 'c:\Users\av\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode'.
tool-uninstall: Finished with code 0.
tool-uninstall: STDOUT:
Tool 'microsoft.dotnet-interactive' was successfully uninstalled and removed from manifest file c:\Users\av\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode\.config\dotnet-tools.json.
tool-install: Executing [dotnet tool install --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json --ignore-failed-sources Microsoft.dotnet-interactive --version 1.0.520801] in 'c:\Users\av\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode'.
tool-install: Finished with code 0.
tool-install: STDOUT:
You can invoke the tool from this directory using the following commands: 'dotnet tool run dotnet-interactive' or 'dotnet dotnet-interactive'.
Tool 'microsoft.dotnet-interactive' (version '1.0.520801') was successfully installed. Entry is added to the manifest file c:\Users\av\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode\.config\dotnet-tools.json.
Started process 20884: dotnet tool run dotnet-interactive -- notebook-parser
Starting kernel for 'file:///c%3A/temp/scripting-notes/notebooks/en/vnet-topology-visualization.ipynb' using: dotnet tool run dotnet-interactive -- [vscode] stdio --working-dir c:\temp\scripting-notes\notebooks\en
Kernel for 'file:///c%3A/temp/scripting-notes/notebooks/en/vnet-topology-visualization.ipynb' started (1888).
process 20884 stderr: Unhandled exception. 
kernel (1888) stderr: Unhandled exception. 
process 20884 stderr: System.IO.FileNotFoundException: Could not load file or assembly 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at Microsoft.DotNet.Interactive.App.Program.<Main>(String[] args)

kernel (1888) stderr: System.IO.FileNotFoundException: Could not load file or assembly 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at Microsoft.DotNet.Interactive.App.Program.<Main>(String[] args)

Process 'dotnet' with PID 20884 exited with code 3762504530 and signal null
Started process 21484: dotnet tool run dotnet-interactive -- notebook-parser
Kernel for 'file:///c%3A/temp/scripting-notes/notebooks/en/vnet-topology-visualization.ipynb' ended (1888) with code 3762504530.
process 21484 stderr: Unhandled exception. 
process 21484 stderr: System.IO.FileNotFoundException: Could not load file or assembly 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.Interactive.App.Program.Main(String[] args)
   at Microsoft.DotNet.Interactive.App.Program.<Main>(String[] args)
```
