### ISSUE TITLE
Raw value storage

### ISSUE THREAD

**Issue by BodukGenius** [dotnet/interactive#3528]
### Describe the bug
I am experiencing a `System.NullReferenceException` error when attempting to set a value using the `#!set` magic command in a .NET Interactive notebook. The error occurs when I try to assign a URL value to a variable in the notebook environment. Below is the error message and stack trace provided:

```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.DotNet.Interactive.KeyValueStoreKernel.Microsoft.DotNet.Interactive.IKernelCommandHandler<Microsoft.DotNet.Interactive.Commands.SubmitCode>.HandleAsync(SubmitCode command, KernelInvocationContext context) in D:\a_work\1\s\src\Microsoft.DotNet.Interactive\KeyValueStoreKernel.cs:line 79
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 330
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 41
```
The notebook content where the issue occurred is as follows:
```
#!meta

{"kernelInfo":{"defaultKernelName":"csharp","items":[{"aliases":[],"name":"csharp"}]}}

#!value

#!set --name url --value https://example.com/
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
Version: 1.0.520801+1e5d205f82c7f5bb1b2e5ce60c680491552cfa23
Library version: 1.0.0-beta.24208.1+1e5d205f82c7f5bb1b2e5ce60c680491552cfa23
Build date: 2024-04-19T23:36:03.3519914Z

- **OS**
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro: _______)
    - [ ] iOS
    - [ ] Android

- **Browser**
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari

- **Frontend**
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify: _______)

### Screenshots
If applicable, add screenshots to help explain your problem. Attach files or drag and drop images here.
![image](https://github.com/dotnet/interactive/assets/3094005/138aeba4-7c01-4c8f-8aba-4312a74f0168)

**Comment by jonsequitur** [comment]
I'm not able to reproduce this bug. Are you still seeing it?
