### ISSUE TITLE
Using NuGet pacakge - System.ArgumentNullException: Value cannot be null. (Parameter 'directory')

### ISSUE THREAD

**Issue by lqdev** [dotnet/interactive#430]
### Describe the bug
When installing a NuGet package and using `open` or `using`, the first time, an error is thrown. Rerunning it makes the error go away and I can use the package.

```text
System.ArgumentNullException: Value cannot be null. (Parameter 'directory')
   at Microsoft.DotNet.Interactive.CompositeKernelExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, CompositeKernel kernel, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectory(DirectoryInfo directory, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.Commands.LoadExtensionsInDirectory.InvokeAsync(KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernel.HandleAsync(IKernelCommand command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _)
   at Microsoft.DotNet.Interactive.KernelBase.<AddSetKernelMiddleware>b__9_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(IKernelCommand command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernelExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, CompositeKernel kernel, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectory(DirectoryInfo directory, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.Commands.LoadExtensionsInDirectory.InvokeAsync(KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.CompositeKernel.HandleAsync(IKernelCommand command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _)
   at Microsoft.DotNet.Interactive.KernelBase.<AddSetKernelMiddleware>b__9_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(IKernelCommand command, KernelInvocationContext context)
```

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/11130940/82226916-1a11b900-98f5-11ea-928d-822a78836084.png)

**Comment by jonsequitur** [comment]
Which version of dotnet-interactive are you using?

I was unable to repro this on 1.0.126511.

![image](https://user-images.githubusercontent.com/547415/82236381-de70f200-98e8-11ea-86d7-5272c36c3037.png)

**Comment by lqdev** [comment]
Forgot to include that. Here you go.

1.0.20071.2+dddd3a6da0c5d77d5641aeedf9ed462b4f7f7983

**Comment by lqdev** [comment]
Makes sense. No wonder I couldn't see the PS kernel option :). I'll close this and open another issue if I have any other problems. Thanks!
