### ISSUE TITLE
Native assemblies in ML.NET no longer seem to work

### ISSUE THREAD

**Issue by eerhardt** [dotnet/interactive#492]
### Describe the bug
The attached notebook doesn't work in the latest builds. It does work on `version '1.0.115407'`

[Notebook.zip](https://github.com/dotnet/interactive/files/4704186/Notebook.zip)

to repro, you will also need the data file here (and change its extension to *.csv.):

[time_series_covid19_confirmed_global_transposed.txt](https://github.com/dotnet/machinelearning/files/4703243/time_series_covid19_confirmed_global_transposed.txt)

```
System.DllNotFoundException: Unable to load DLL 'MklImports' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Microsoft.ML.Transforms.TimeSeries.EigenUtils.Dsytrd(Layout matrixLayout, Uplo uplo, Int32 n, Double[] a, Int32 lda, Double[] d, Double[] e, Double[] tau)
   at Microsoft.ML.Transforms.TimeSeries.EigenUtils.MklSymmetricEigenDecomposition(Single[] input, Int32 size, Single[]& eigenValues, Single[]& eigenVectors)
   at Microsoft.ML.Transforms.TimeSeries.TrajectoryMatrix.ComputeSvd(Single[]& singularValues, Single[]& leftSingularvectors)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.TrainCore(Single[] dataArray, Int32 originalSeriesLength)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.Train(RoleMappedData data)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingTransformer..ctor(IHostEnvironment env, Options options, IDataView input)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingEstimator.Fit(IDataView input)
   at Submission#24.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.ML.Transforms.TimeSeries.EigenUtils.Dsytrd(Layout matrixLayout, Uplo uplo, Int32 n, Double[] a, Int32 lda, Double[] d, Double[] e, Double[] tau)
   at Microsoft.ML.Transforms.TimeSeries.EigenUtils.MklSymmetricEigenDecomposition(Single[] input, Int32 size, Single[]& eigenValues, Single[]& eigenVectors)
   at Microsoft.ML.Transforms.TimeSeries.TrajectoryMatrix.ComputeSvd(Single[]& singularValues, Single[]& leftSingularvectors)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.TrainCore(Single[] dataArray, Int32 originalSeriesLength)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.Train(RoleMappedData data)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingTransformer..ctor(IHostEnvironment env, Options options, IDataView input)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingEstimator.Fit(IDataView input)
   at Submission#24.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

```
.NET Interactive

© 2020 Microsoft Corporation

Version: 1.0.126302+9e8f007038a86132f72a94889d805be2a14addf2

Build date: 2020-05-29T22:36:19.8099647Z

https://github.com/dotnet/interactive
```

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [x] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

Working on `--version 1.0.115407`

![image](https://user-images.githubusercontent.com/8291187/83303292-68ab3700-a1c2-11ea-9460-a7f754075d0d.png)

Failing on `--version 1.0.126302`

![image](https://user-images.githubusercontent.com/8291187/83303667-16b6e100-a1c3-11ea-980a-7aa04c626693.png)

cc @jonsequitur @colombod @KevinRansom

**Comment by KevinRansom** [comment]
@Eric Eilebrecht<mailto:ericeil@microsoft.com>, I broke it, I fixed it in the F# branch earlier in the week, and today we merged the fix into the notebook master branch.


I tried to run your notebook, and it couldn’t load “c:\Temp\time_series_covid19_confirmed_global_transposed.csv”  but I believe package management works again.
System.IO.FileNotFoundException: Could not find file 'c:\Temp\time_series_covid19_confirmed_global_transposed.csv'.
File name: 'c:\Temp\time_series_covid19_confirmed_global_transposed.csv'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Submission#46.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Submission#46.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

**Comment by eerhardt** [comment]
> I tried to run your notebook, and it couldn’t load “c:\Temp\time_series_covid19_confirmed_global_transposed.csv”

I updated the top post with a link to the data file (which needs to be renamed to `.csv`)

**Comment by KevinRansom** [comment]
@eerhardt thanks mate.

**Comment by KevinRansom** [comment]
@eerhardt ,

yes it's fixed:
![image](https://user-images.githubusercontent.com/5175830/83313623-eaec2900-a1cb-11ea-86d4-de97a3b4ea99.png)

**Comment by KevinRansom** [comment]
That's with a fresh build of master branch.

**Comment by praveenraghuvanshi1512** [comment]
I followed the instruction to uninstall and install donet-interactive as per below commands and it starts to throw error.  Kernel is not starting

> dotnet tool uninstall -g microsoft.dotnet-interactive
> dotnet tool install -g microsoft.dotnet-interactive --version 1.0.115407

![image](https://user-images.githubusercontent.com/39731863/83316558-1874b900-a244-11ea-99ea-c448fc1e23c2.png)

In Jupyter notebook, it kernel keeps crashing. Now I can't run C# Jupyter notebook

**Comment by colombod** [comment]
That version had a bug related to command line parsing. Could you use at least version 1.0.127906

**Comment by praveenraghuvanshi1512** [comment]
1.0.127906 is throwing error

![image](https://user-images.githubusercontent.com/39731863/83317030-735bdf80-a247-11ea-82f0-9f83ed7898e5.png)

Initially i have below version in which only few commands were failing... Now kernel itself is crashing. Can we connect somehow to troubleshoot as I have a presentation tomorrow?

**Comment by praveenraghuvanshi1512** [comment]
I have rolled back to my inital version 1.0.126302, no crash observed, but issue in https://github.com/dotnet/machinelearning/issues/5178 still holds good with DllNotFoundException 'MklImports'

**Comment by colombod** [comment]
The latest version is available from the myget feed

**Comment by praveenraghuvanshi1512** [comment]
What is the version # ?

I tried with https://dotnet.myget.org/gallery/interactive-window and executed below commands to install.

>dotnet tool install -g --add-source "https://dotnet.myget.org/F/interactive-window/api/v3/index.json" Microsoft.dotnet-interactive

>dotnet tool list -g
Package Id                        Version             Commands
------------------------------------------------------------------------
dotnet-try                        1.0.19553.4         dotnet-try
microsoft.dotnet-interactive      1.0.115407          dotnet-interactive  <<------
microsoft.quantum.iqsharp         0.10.1911.1607      dotnet-iqsharp
mlnet                             0.15.1              mlnet

It installed v1.0.115407, post that kernel is crashing again with  error 'File does not exist and command not found'.

Did I miss something here?

**Comment by colombod** [comment]
Executing the command 
```
> dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-interactive
```

I see the following output

```
You can invoke the tool using the following command: dotnet-interactive
Tool 'microsoft.dotnet-interactive' (version '1.0.127908') was successfully installed.
```

I can open the HousingML notebook from the samples without kernel crash.

loading the packages seems to work
![image](https://user-images.githubusercontent.com/375556/83324956-84fdb100-a260-11ea-818f-a9c2cad17434.png)

And the rest of the notebook executes just fine

I have not reinstalled the kernel specs but might be worth for you to try reinstall them?

If you are using anaconda and conda environment open your conda prompt and perform again the command 
```
> dotnet interactive jupyter install
```

**Comment by praveenraghuvanshi1512** [comment]
Awesome v1.0.127908 worked and pipeline.Fit() for time series prediction also worked.
Last time myget installed a different version 1.0.115407 which was crashing.

@colombod  Thanks for the fix.

**Comment by colombod** [comment]
It is my pleasure, happy you have all working perfectly now!

**Comment by colombod** [comment]
Would love to see your new features!

**Comment by praveenraghuvanshi1512** [comment]
Yes... issue can be closed
When we'll get the fix as part of nuget package for dotnet-interactive?

**Comment by jonsequitur** [comment]
The fixed version of the package is available on this feed: 

https://dotnet.myget.org/F/dotnet-try/api/v3/index.json

We're making a few breaking changes to our APIs and probably won't push to nuget.org until those are done, in order to minimize the number of times we introduce breaking changes there.

**Comment by eerhardt** [comment]
Closing as this has been addressed.
