### ISSUE TITLE
Unhandled Exception when loading nuget package from jupyter c-sharp notebook

### ISSUE THREAD

**Issue by yduit** [dotnet/interactive#545]
#### Describe the bug
When installing any nuget package using for example: #r "nuget:Microsoft.Data.Analysis" using VS 2019 16.7.0 preview2.0

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [x] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
Installing package Microsoft.Data.Analysis......done!
Unhandled Exception
No design time or full build available
   at WorkspaceServer.Packaging.Package.CreateRoslynWorkspace()
   at WorkspaceServer.Packaging.Package.ProcessFullBuildRequest(Budget budget)
   at WorkspaceServer.Packaging.Package.<SetupWorkspaceCreationFromBuildChannel>b__54_0(Budget budget)
   at WorkspaceServer.Packaging.PackageRestoreContext.CreatePackage(String name)
   at WorkspaceServer.Packaging.PackageRestoreContext.AddPackage(String packageName, String packageVersion)
   at WorkspaceServer.Kernel.CSharpKernelExtensions.<>c__DisplayClass2_1.<<UseNugetDirective>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.Commands.KernelCommandBase.InvokeAsync(KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelBase.HandleInternalAsync(IKernelCommand command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _)
   at Microsoft.DotNet.Interactive.KernelBase.<AddSetKernelMiddleware>b__8_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(IKernelCommand command, KernelInvocationContext context)
#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Jupyter support has moved from `dotnet-try` to `dotnet-interactive`. Please uninstall `dotnet-try` and follow the install instructions [here](https://github.com/dotnet/interactive/blob/master/docs/NotebooksLocalExperience.md), and let us know if this resolves the issue.

**Comment by yduit** [comment]
Works great after uninstalled dotnet-try and then installed dotnet-interactive:
`jupyter kernelspec uninstall .net-fsharp`
`jupyter kernelspec uninstall .net-csharp`
`dotnet tool uninstall -g dotnet-try`
