### ISSUE TITLE
JavaScript does not work; the kernel or host throws a null reference exception

### ISSUE THREAD

**Issue by cveld** [dotnet/interactive#589]
### Describe the bug
I installed the extension in Visual Studio Code Insiders and I am not able to run a JavaScript interactive cell.
Cell test contents:
```
console.log('test')
```

Exception copied below.

### Please complete the following:

**Which version of .NET Interactive are you using?** 
Version: 1.0.132609+29c04d2c9fbbf3b6975d8e76d2abd62097db285b
Build date: 2020-06-27T12:53:18.3665518Z

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Exception
```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass7_0.<SetUpFormatters>b__2(ScriptContent script, TextWriter writer) in F:\workspace\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 529
at Microsoft.DotNet.Interactive.Formatting.AnonymousTypeFormatter`1.Format(T instance, TextWriter writer) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\AnonymousTypeFormatter{T}.cs:line 27
at Microsoft.DotNet.Interactive.Formatting.TypeFormatter`1.Microsoft.DotNet.Interactive.Formatting.ITypeFormatter.Format(Object instance, TextWriter writer) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\TypeFormatter{T}.cs:line 19
at Microsoft.DotNet.Interactive.Formatting.Formatter`1.FormatTo(T obj, TextWriter writer, String mimeType) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter{T}.cs:line 93
at Microsoft.DotNet.Interactive.Formatting.Formatter.FormatTo[T](T obj, TextWriter writer, String mimeType) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter.cs:line 278
at Microsoft.DotNet.Interactive.Formatting.Formatter.ToDisplayString(Object obj, String mimeType) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\Formatter.cs:line 242
at Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.Display(KernelInvocationContext context, Object value, String mimeType) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelInvocationContextExtensions.cs:line 33
at Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.DisplayAsync(KernelInvocationContext context, Object value, String mimeType) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelInvocationContextExtensions.cs:line 20
at Microsoft.DotNet.Interactive.JavaScriptKernel.HandleAsync(SubmitCode command, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\JavaScriptKernel.cs:line 24
at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 48
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 293
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 56
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 119
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.<AddDirectiveMiddlewareAndCommonCommandHandlers>b__21_0(KernelCommand originalCommand, KernelInvocationContext context, KernelPipelineContinuation next) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 125
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.SetKernel(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 221
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.<>c.<<AddCaptureConsoleMiddleware>b__20_0>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 48
```

**Comment by jonsequitur** [comment]
This appears to repro only if the first code submission is JavaScript. Can you confirm that this is the behavior you're seeing?

**Comment by cveld** [comment]
What I find confusing is how to init a new notebook. There doesn't seem to be a "New notebook" experience. And if I just create a new file, save it ".dib", it does not automatically convert into a notebook. I need to reopen it first.

Secondly, mostly the JavaScript workload doesn't output at my side at all. See the following screenshot:

![image](https://user-images.githubusercontent.com/6196260/85946364-3406d880-b944-11ea-8e99-03a870b99f07.png)

Your hypothesis seems right that javascript only throws a null reference exception when this is the first workload that is run in the kernel. I did the following:
1. Open dib file
2. Play javascript -> throws
3. Play c#
4. Play javascript -> just empty
5. Restart kernel
6. Play javascript -> throws 
7. Play c#
8. Play javascript -> just empty

**Comment by jonsequitur** [comment]
We're not capturing `console.log` currently in the VS Code experience, though it seems like it would be useful. I've opened #591 to track this.

**Comment by cveld** [comment]
How do I test whether the javascript engine can export anything? E.g. `throw` does not output anything as well.

![image](https://user-images.githubusercontent.com/6196260/85998785-8e1ea100-ba0b-11ea-98d6-89f1acac1f36.png)


So far I haven't seen any output other than that null reference exception.

**Comment by jonsequitur** [comment]
You can insert elements into the DOM and manipulate them.

**Comment by cveld** [comment]
Do you have a small example to work with?

**Comment by jonsequitur** [comment]
Also note that you can put both of these into a single cell so that the JavaScript output appears in a more intuitive location:

![image](https://user-images.githubusercontent.com/547415/86051096-bad1b900-ba09-11ea-82af-3e092a880950.png)
