### ISSUE TITLE
SQLiteKernel - Unable to load shared library 'e_sqlite3'  #723

### ISSUE THREAD

**Issue by rspaulino** [dotnet/interactive#743]
### Describe the bug
Please provide as much information as you can.

Testing #723 SQLiteKernel extension

I try all this nuget packages in different combination(NOT all at once) and non resolve the issue.
```
#r "nuget:sqlite-net-pcl,1.7.335"
#r "nuget:Microsoft.Data.Sqlite"
#r "nuget:SQLitePCLRaw.bundle_green,2.0.4-pre20200828111558"
#r "nuget:nuget:SQLitePCLRaw.core"
#r "nuget:SQLitePCLRaw.lib.e_sqlite3.osx,1.1.14"
#r "nuget:SQLitePCLRaw.lib.e_sqlite3,2.0.4-pre20200828111558"
#r "nuget:SQLitePCLRaw.provider.e_sqlite3.netstandard11,1.1.14"
#r "nuget:SQLitePCLRaw.provider.e_sqlite3,2.0.4-pre20200828111558"
```

```
Error: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libe_sqlite3, 1): image not found
at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
at SQLitePCL.Batteries_V2.Init()
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
at Microsoft.Data.Sqlite.SqliteConnection..cctor()
--- End of inner exception stack trace ---
at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
at Microsoft.DotNet.Interactive.ExtensionLab.SQLiteKernel.OpenConnection()
at Microsoft.DotNet.Interactive.ExtensionLab.SqlKernel.HandleAsync(SubmitCode submitCode, KernelInvocationContext context)
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/Kernel.cs:line 291
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 57
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/CompositeKernel.cs:line 146
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.<AddDirectiveMiddlewareAndCommonCommandHandlers>b__21_0(KernelCommand originalCommand, KernelInvocationContext context, KernelPipelineContinuation next) in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/Kernel.cs:line 126
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.SetKernel(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/Kernel.cs:line 218
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.<>c.<<AddCaptureConsoleMiddleware>b__20_0>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/Kernel.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in /Users/rspaulino/Downloads/vscodeprojects/microsoftprojects/interactive/src/Microsoft.DotNet.Interactive/KernelCommandPipeline.cs:line 42
```
### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

```
local build from the lastest commit 29ee905 at that time.
```

- OS
    - [ ] Windows 10
    - [X] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
<img width="1553" alt="Screen Shot 2020-09-02 at 11 53 17 AM" src="https://user-images.githubusercontent.com/378671/92006579-ea0aec00-ed12-11ea-9ffe-485e9822f117.png">

**Comment by jhoneill** [comment]
Just a "me too" 
I get it opening 
https://github.com/dotnet/interactive/blob/main/samples/ExtensionLab/ExtensionLab-SQL%20connections.dib 
Windows 10.0.19041,  
vscode 1.150.0  
dotNetInteractive 1.0.146902

**Comment by KevinRansom** [comment]
@jonsequitur 
I think the repro above, may has a typo:
````
#r "nuget:SQLitePCLRaw.core"
````
When fixed:
````
#r "nuget:sqlite-net-pcl,1.7.335"
#r "nuget:Microsoft.Data.Sqlite"
#r "nuget:SQLitePCLRaw.bundle_green,2.0.4-pre20200828111558"
#r "nuget:SQLitePCLRaw.core"
#r "nuget:SQLitePCLRaw.lib.e_sqlite3.osx,1.1.14"
#r "nuget:SQLitePCLRaw.lib.e_sqlite3,2.0.4-pre20200828111558"
#r "nuget:SQLitePCLRaw.provider.e_sqlite3.netstandard11,1.1.14"
#r "nuget:SQLitePCLRaw.provider.e_sqlite3,2.0.4-pre20200828111558"
````

This produces this output:

- Installing package SQLitePCLRaw.lib.e_sqlite3.osx, version 1.1.14.........
- Installed package SQLitePCLRaw.bundle_green version 2.0.4-pre20200828111558
- Installing package SQLitePCLRaw.provider.e_sqlite3.netstandard11, version 1.1.14.........
- Installing package Microsoft.Data.Sqlite.........
- Installed package SQLitePCLRaw.lib.e_sqlite3 version 2.0.4-pre20200828111558
- Installed package SQLitePCLRaw.provider.e_sqlite3 version 2.0.4-pre20200828111558
- Installed package sqlite-net-pcl version 1.7.335
- Installed package SQLitePCLRaw.core version 2.0.4

Note:
- Installing package SQLitePCLRaw.lib.e_sqlite3.osx, version 1.1.14.........
- Installing package SQLitePCLRaw.provider.e_sqlite3.netstandard11, version 1.1.14.........
- Installing package Microsoft.Data.Sqlite.........

It is stuck on installing.  I will address that first and then see if the loading problem still occurs.

**Comment by KevinRansom** [comment]
I verified that this works now:
I used ExtensionsLab-SQL connections.dib to verify it.

![image](https://user-images.githubusercontent.com/5175830/106802967-83b72c00-6618-11eb-97d0-f1195e2b4ed0.png)
