### ISSUE TITLE
NuGet packages with native assets in a notebook

### ISSUE THREAD

**Issue by eerhardt** [dotnet/interactive#75]
#### Describe the bug
When using the [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML/) NuGet package in a notebook, you get an exception when ML.NET calls into a native assembly.

#### Repro

Run the following notebook:

```C#
#r "nuget:Microsoft.ML"
    
using Microsoft.ML;
using Microsoft.ML.Data;

class IrisData
{
    public IrisData(float sepalLength, float sepalWidth, float petalLength, float petalWidth)
    {
        SepalLength = sepalLength;
        SepalWidth = sepalWidth;
        PetalLength = petalLength;
        PetalWidth = petalWidth;
    }
    public float SepalLength;
    public float SepalWidth;
    public float PetalLength;
    public float PetalWidth;
}

var data = new []
{
    new IrisData(1.4f, 1.3f, 2.5f, 4.5f), 
    new IrisData(2.4f, 0.3f, 9.5f, 3.4f), 
    new IrisData(3.4f, 4.3f, 1.6f, 7.5f), 
    new IrisData(3.9f, 5.3f, 1.5f, 6.5f), 
};

MLContext mlContext = new MLContext();
var pipeline = mlContext.Transforms
    .Concatenate("Features", "SepalLength", "SepalWidth", "PetalLength", "PetalWidth")
    .Append(mlContext.Clustering.Trainers.KMeans("Features", numberOfClusters: 2));

try
{
    pipeline.Fit(mlContext.Data.LoadFromEnumerable(data));
}
catch (Exception e)
{
    Console.WriteLine(e);
}
```
This shouldn't throw an exception, but it does:

```
System.DllNotFoundException: Unable to load shared library 'CpuMathNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libCpuMathNative, 1): image not found
   at Microsoft.ML.Internal.CpuMath.Thunk.SumSqU(Single* ps, Int32 c)
   at Microsoft.ML.Internal.CpuMath.CpuMathUtils.SumSq(ReadOnlySpan`1 src)
   at Microsoft.ML.Numeric.VectorUtils.NormSquared(VBuffer`1& a)
   at Microsoft.ML.Trainers.KMeansBarBarInitialization.Initialize(IHost host, Int32 numThreads, IChannel ch, Factory cursorFactory, Int32 k, Int32 dimensionality, VBuffer`1[] centroids, Int64 accelMemBudgetMb, Int64& missingFeatureCount, Int64& totalTrainingInstances)
   at Microsoft.ML.Trainers.KMeansTrainer.TrainCore(IChannel ch, RoleMappedData data, Int32 dimensionality)
   at Microsoft.ML.Trainers.KMeansTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Submission#6.<<Initialize>>d__0.MoveNext()
```

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots

<img width="1030" alt="Screen Shot 2019-07-27 at 12 31 07 PM" src="https://user-images.githubusercontent.com/8291187/62084868-e065a980-b21f-11e9-83f8-988842d03837.png">

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by KevinRansom** [comment]
@eerhardt,  I think your observation is valid, that the most specific rids would not be selected.

I think the only reasonable solution would be to extend #r "nuget: to include a specified rid, and search for that native rid.

Otherwise I don't really know how we would identify the specific sku, given that the dotnet-interactive.exe itself will have been compiled to be one of those simple rids.

Kevin

**Comment by eerhardt** [comment]
The way this works for a "normal" app is the following:

1. At build time, a `.deps.json` file is created that contains information on which native assets are needed based on which RID the current machine is. For example:

```json
"LibGit2Sharp.NativeBinaries/2.0.306": {
    "runtimeTargets": {
        "runtimes/alpine-x64/native/libgit2-106a5f2.so": {
            "rid": "alpine-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/alpine.3.9-x64/native/libgit2-106a5f2.so": {
            "rid": "alpine.3.9-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/debian-arm64/native/libgit2-106a5f2.so": {
            "rid": "debian-arm64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/linux-x64/native/libgit2-106a5f2.so": {
            "rid": "linux-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/osx/native/libgit2-106a5f2.dylib": {
            "rid": "osx",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/win-x64/native/git2-106a5f2.dll": {
            "rid": "win-x64",
            "assetType": "native",
            "fileVersion": "0.28.4.0"
        }
        // ... etc
    }
}
```

This `.deps.json` file (a runtime artifact) is created from the NuGet `project.asset.json` file (a build-time artifact).

2. The `dotnet.exe` host uses the `.deps.json` file + [the current machine's RID](https://github.com/dotnet/runtime/blob/69fdb2e2e7b027b0e253e75d34bcffd3c3f08588/src/installer/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L31) + the `RID fallback graph` to determine the most appropriate native asset to load.

The `RID fallback graph` is retrieved by looking at the shared framework's `.deps.json` file, which can be found at `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\<version>\Microsoft.NETCore.App.deps.json` or by calling `AppContext.GetData("FX_DEPS_FILE")` like [the CLI does](https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/Microsoft.DotNet.Cli.Utils/FrameworkDependencyFile.cs#L27). This `.deps.json` file is special because it contains a `"runtimes"` section, which says which order of RIDs to probe given a starting RID. For example:

```
  "runtimes": {
    "win10-x64": [
      "win10",
      "win81-x64",
      "win81",
      "win8-x64",
      "win8",
      "win7-x64",
      "win7",
      "win-x64",
      "win",
      "any",
      "base"
    ],
```

If the current machine is a `win10-x64` machine, first try that RID, then try `win10`, then `win81-x64`, etc.

That's how "normal" apps work.

In 3.0, we added a new API to help with this scenario. See https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#load-plugins. Basically you create an `AssemblyDependencyResolver`, and call `.ResolveUnmanagedDllToPath(unmanagedDllName)`. However, the issue here is that you would need a `.deps.json` file sitting next to the path you passed in to the `AssemblyDependencyResolver`. How we would create that `.deps.json` file during `dotnet-interactive` is not clear to me.

My current thinking is that we could get by with inspecting the `project.assets.json` file that we get from a NuGet restore + the `RID fallback graph` I described above.

See also my comments [here](https://github.com/dotnet/try/pull/600#pullrequestreview-312776854).

**Comment by KevinRansom** [comment]
@eerhardt, that would require a developer gesture to specify the target rid in their script.

For example:
     #nuget targetrid=tizen.5.0.0

It doesn't seem as if there is any way we can infer this.  What do you think?

**Comment by eerhardt** [comment]
> that would require a developer gesture to specify the target rid in their script.

> It doesn't seem as if there is any way we can infer this

Why? There is only 1 machine the script is currently running on: the current machine. 

Or are we expecting that the interactive environment would restore NuGet packages on one machine, and then attempt to execute them on a completely different machine?

In `3.1` and previous versions, you can get the current machine's RID by calling [`RuntimeEnvironment.GetRuntimeIdentifier()`](https://github.com/dotnet/core-setup/blob/release/3.1/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L31-L36).
In `5.0`, we have added a property to `RuntimeInformation` - see https://github.com/dotnet/runtime/pull/34206.

**Comment by jonsequitur** [comment]
> Or are we expecting that the interactive environment would restore NuGet packages on one machine, and then attempt to execute them on a completely different machine?

Not at the moment, and even if we look into this later, it'll go through a standard and explicit publish gesture.

**Comment by KevinRansom** [comment]
@eerhardt, well, there aren't any apis that will allow us to infer the target rid for lets say tizen.5.0.0.  Either a developer would have to type that, because he knows, or we write some code to discover it.

Which I'm guessing would be error-prone, especially for platforms, we don't have access to.  It should be noted that the target rid is supplied as a command line argument qhwn building projects.

**Comment by KevinRansom** [comment]
Thats why the current probing logic is limited, what it discovers can be easily inferred from existing apis.

**Comment by KevinRansom** [comment]
@eerhardt Am I right, PlatformAbstractions, has a get current rid api.  Thats pretty groovy.

**Comment by KevinRansom** [comment]
Nice ...
````
#r "nuget:Microsoft.DotNet.PlatformAbstractions, 3.1.3"
Console.WriteLine("{0}", Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier())
````
Installed package Microsoft.DotNet.PlatformAbstractions version 3.1.3
win10-x64

**Comment by eerhardt** [comment]
Yep, that's the one! That's how you can get the RID of the current machine. The user shouldn't need to supply it at all.

**Comment by KevinRansom** [comment]
@eerhardt thats neat.

**Comment by colombod** [comment]
Is this issue still on?

**Comment by KevinRansom** [comment]
yes ... it will get done ... eventually.

**Comment by eerhardt** [comment]
>  That's how you can get the RID of the current machine.

FYI - we added a new API in `5.0` to get the RID of the current machine:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.runtimeidentifier

**Comment by ericstj** [comment]
> How we would create that .deps.json file during dotnet-interactive is not clear to me.
> My current thinking is that we could get by with inspecting the project.assets.json file that we get from a NuGet restore + the RID fallback graph I described above.

Does dotnet-interactive run a restore on the packages it loads?  If it did, it shouldn't be too much more to generate a deps file for that assembly.  According to https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#load-plugins

> It resolves assemblies and native libraries to their relative paths based on the .deps.json file for the class library whose path was passed to the AssemblyDependencyResolver constructor. The custom AssemblyLoadContext enables plugins to have their own dependencies, and the AssemblyDependencyResolver makes it easy to correctly load the dependencies.

Here's a quick sample I threw together that produces a deps file for a package.
```
<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="GenerateBuildDependencyFile">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IncludeMainProjectInDepsFile>false</IncludeMainProjectInDepsFile>
    <NoBuild>true</NoBuild>
    <ProjectDepsFileName>Microsoft.ML.deps.json</ProjectDepsFileName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="1.5.5" />
  </ItemGroup>

</Project>
```
