### ISSUE TITLE
Create new emptynotebook does not let me write in cells

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#782]
Open vscode
create new empty .NET Interactive notebook
cannot type in any cell

**Which version of .NET Interactive are you using?**
1.0.146501

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

**Comment by brettfo** [comment]
Output log shows:

```
[2020-09-15 10:35:34.033] [renderer3] [error] A notebook with view type 'dotnet-interactive-jupyter' already exists for 'untitled:Untitled-1.ipynb', CANNOT create another notebook with view type jupyter-notebook: Error: A notebook with view type 'dotnet-interactive-jupyter' already exists for 'untitled:Untitled-1.ipynb', CANNOT create another notebook with view type jupyter-notebook
    at e.resolve (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6316:132)
    at X.provideTextContent (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7565:289)
    at S.resolveTextModelContent (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6439:164)
    at S.doCreateReferencedObject (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6438:52)
    at S.createReferencedObject (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6437:487)
    at S.acquire (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:89:355)
    at b.createModelReference (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6439:835)
    at a.resolveTextModelRef (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3401:645)
    at u.resolveTextModel (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3523:914)
    at new f (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3563:709)
    at d._createInstance (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1687:671)
    at d.createInstance (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1687:92)
    at e.renderElement (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3987:476)
    at W.renderElement (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:569:673)
    at E.insertItemInDOM (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:540:745)
    at E._splice (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:536:710)
    at E.splice (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:535:328)
    at file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:575:688
    at t.EventBufferer.bufferEvents (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:98:523)
    at b.splice (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:575:655)
    at b.splice2 (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3485:72)
    at b.attachViewModel (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3483:512)
    at e._attachModel (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7504:385)
    at async e.setModel (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7495:756)
    at async e.setInput (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7553:817)
    at async p.doSetInput (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4731:797)
    at async p.openEditor (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4730:425)
    at async file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6685:617
    at async e.openEditor (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6684:121)
    at async F.openEditor (file:///C:/Users/Brett/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6457:31)

```

**Comment by colombod** [comment]
Fixed with [PR](https://github.com/microsoft/vscode/pull/106313)
