### ISSUE TITLE
Error in creating dbcontext

### ISSUE THREAD

**Issue by hosseinnassiri** [dotnet/interactive#883]
I tried using .net interactive and creating dbcontext from my sqllocaldb with this command:
`#!connect mssql --create-dbcontext True --kernel-name eshop "Integrated Security=true; Initial Catalog=eShopDashboard; Data Source=(LocalDb)\\MSSQLLocalDB;"`

it fails throwing this error:
```
Error: System.InvalidOperationException: Path to SQL Tools Service executable was not provided.
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlServiceClient.StartProcessAndRedirectIO()
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlServiceClient.Initialize()
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlKernel..ctor(String name, String connectionString)
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlKernelConnection.CreateKernelAsync(MsSqlConnectionOptions options, KernelInvocationContext context)
at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass26_0`1.<<AddKernelConnection>b__0>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 319
--- End of stack trace from previous location where exception was thrown ---
at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 35
at Microsoft.DotNet.Interactive.Kernel.<AddDirectiveMiddlewareAndCommonCommandHandlers>b__21_0(KernelCommand originalCommand, KernelInvocationContext context, KernelPipelineContinuation next) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 134
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.SetKernel(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 219
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.Kernel.<>c.<<AddCaptureConsoleMiddleware>b__20_0>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 48
```

- .Net Interactive version: 1.0.156101+537f46e89a1690a55315d805eb90a5877aff9de2
- OS: Windows 10
- Frontend: Visual Studio Code

### Screenshots
![image](https://user-images.githubusercontent.com/18518616/99338511-54cbbe00-2852-11eb-96ff-3901d97c1619.png)

**Comment by jonsequitur** [comment]
We're working on providing the SQL Tool Service executable via a NuGet package, at which point this will be a lot smoother, but for the moment you can do this to work around it:

* Download and unzip the [SQL Tools Service](https://github.com/microsoft/sqltoolsservice/releases/tag/v3.0.0-release.56)
* Store the path to `MicrosoftSqlToolsServiceLayer.exe` in an environment variable called `DOTNET_SQLTOOLSSERVICE`

**Comment by hosseinnassiri** [comment]
> * DOTNET_SQLTOOLSSERVICE

Thanks Jon for the help. 
but now it's throwing another error: Access is Denied
I'm trying to connect to my (LocalDb)\MSSQLLocalDB whe I'm receiving this error. is there any limitation?
I tried with SQL Login and Integrated Security, same error for both:
```
Error: System.ComponentModel.Win32Exception (5): Access is denied.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlServiceClient.StartProcessAndRedirectIO()
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlServiceClient.Initialize()
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlKernel..ctor(String name, String connectionString)
at Microsoft.DotNet.Interactive.ExtensionLab.MsSqlKernelConnection.CreateKernelAsync(MsSqlConnectionOptions options, KernelInvocationContext context)
at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass26_0`1.<<AddKernelConnection>b__0>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 319
```

**Comment by jonsequitur** [comment]
I haven't tried this with LocalDB. 

@chlafreniere @corivera Any ideas?

**Comment by corivera** [comment]
Looks like that error is from failing to start MicrosoftSqlToolsServiceLayer.exe. That's before we open any connections.

https://github.com/dotnet/interactive/blob/main/src/Microsoft.DotNet.Interactive.ExtensionLab/MsSqlServiceClient.cs#L53

**Comment by jonsequitur** [comment]
This should now work using the latest packages from our CI feeds:

```csharp
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json"
#r "nuget:Microsoft.DotNet.Interactive.ExtensionLab,*-*"
```
